# Generated by Django 5.2.17 on 2026-09-22 13:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('teachers', '0008_teacherpedagogicalpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آزمون')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات آزمون')),
                ('instructions', models.TextField(blank=True, default='', verbose_name='دستورالعمل آزمون')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='مدت زمان آزمون (دقیقه)')),
                ('anti_cheat_config', models.JSONField(blank=True, default=dict, verbose_name='تنظیمات ضد تقلب')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='ترتیب تصادفی سوالات')),
                ('shuffle_choices', models.BooleanField(default=False, verbose_name='ترتیب تصادفی گزینهها')),
                ('passing_score', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5, verbose_name='نمره قبولی (درصد)')),
                ('max_attempts', models.PositiveIntegerField(default=1, verbose_name='حداکثر دفعات شرکت')),
                ('status', models.CharField(choices=[('draft', 'پیشنویس'), ('published', 'منتشر شده'), ('closed', 'پایان یافته'), ('archived', 'بایگانی شده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت')),
                ('access_code', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='کد دسترسی آزمون')),
                ('show_results_to_student', models.BooleanField(default=True, verbose_name='نمایش نتایج به زبانآموز')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع آزمون')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان آزمون')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
                ('teacher_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_exams', to='teachers.teacherclass', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'آزمون آنلاین',
                'verbose_name_plural': 'آزمونهای آنلاین',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='شماره تلاش')),
                ('status', models.CharField(choices=[('in_progress', 'در حال انجام'), ('submitted', 'ارسال شده'), ('auto_graded', 'تصحیح خودکار'), ('manually_graded', 'تصحیح دستی'), ('timed_out', 'مهلت تمام شده')], db_index=True, default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='نمره کسب شده')),
                ('max_possible_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='حداکثر نمره ممکن')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درصد نمره')),
                ('integrity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره اصالت')),
                ('integrity_details', models.JSONField(blank=True, default=dict, verbose_name='جزئیات نمره اصالت')),
                ('is_late', models.BooleanField(default=False, verbose_name='ثبت با تاخیر')),
                ('time_limit_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='مهلت پایان تایمر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to=settings.AUTH_USER_MODEL, verbose_name='زبانآموز')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='online_exams.onlineexam', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'پاسخنامه آزمون',
                'verbose_name_plural': 'پاسخنامههای آزمون',
                'ordering': ['-started_at'],
                'unique_together': {('exam', 'student', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='نمره سوال')),
                ('custom_instructions', models.TextField(blank=True, default='', verbose_name='دستورالعمل سفارشی')),
                ('listening_play_limit', models.PositiveIntegerField(default=2, verbose_name='سقف دفعات پخش صوت')),
                ('speaking_time_limit_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='محدودیت زمان ضبط صدا (ثانیه)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_usages', to='questions.questionversion', verbose_name='نسخه سوال')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='online_exams.onlineexam', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'سوال آزمون',
                'verbose_name_plural': 'سوالات آزمون',
                'ordering': ['order', 'created_at'],
                'unique_together': {('exam', 'question_version')},
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_response', models.JSONField(blank=True, default=dict, verbose_name='پاسخ زبانآموز')),
                ('audio_recording_url', models.URLField(blank=True, default='', verbose_name='آدرس فایل ضبط صدا')),
                ('is_auto_graded', models.BooleanField(default=False, verbose_name='تصحیح خودکار شده')),
                ('auto_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره خودکار')),
                ('manual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره دستی')),
                ('score_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره نهایی')),
                ('teacher_feedback', models.TextField(blank=True, default='', verbose_name='بازخورد مدرس')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تصحیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_exam_answers', to=settings.AUTH_USER_MODEL, verbose_name='مصحح')),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='online_exams.examquestion', verbose_name='سوال آزمون')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='online_exams.examsubmission', verbose_name='پاسخنامه')),
            ],
            options={
                'verbose_name': 'پاسخ سوال',
                'verbose_name_plural': 'پاسخهای سوالات',
                'ordering': ['exam_question__order'],
                'unique_together': {('submission', 'exam_question')},
            },
        ),
        migrations.CreateModel(
            name='ProctoringLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('blur', 'خروج از صفحه'), ('focus', 'ورود به صفحه'), ('tab_hidden', 'مخفی شدن تب'), ('tab_visible', 'نمایش تب'), ('fullscreen_exit', 'خروج از تمامصفحه'), ('fullscreen_enter', 'ورود به تمامصفحه'), ('paste_attempt', 'تلاش برای الصاق (Paste)'), ('devtools_attempt', 'تلاش برای باز کردن DevTools'), ('shortcut_blocked', 'مسدود شدن میانبر'), ('window_resize', 'تغییر اندازه پنجره'), ('exam_started', 'شروع آزمون'), ('exam_submitted', 'پایان آزمون')], db_index=True, max_length=30, verbose_name='نوع رویداد')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='مدت زمان (ثانیه)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت سرور')),
                ('client_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت کلاینت')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تکمیلی')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_logs', to='online_exams.examsubmission', verbose_name='پاسخنامه')),
            ],
            options={
                'verbose_name': 'لاگ نظارت',
                'verbose_name_plural': 'لاگهای نظارت',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['submission', 'event_type'], name='online_exam_submiss_c66754_idx'), models.Index(fields=['submission', 'timestamp'], name='online_exam_submiss_230cf3_idx')],
            },
        ),
    ]
