# Generated by Django 5.2.17 on 2026-09-05 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PronunciationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('category', models.CharField(choices=[('minimal_pairs', 'Minimal Pairs (جفت\u200cهای کمینه)'), ('stress_shifts', 'Syllable Stress Shifts (جابجایی استرس)'), ('consonant_clusters', 'Consonant Clusters & Epenthesis (خوشه\u200cهای همخوانی)'), ('connected_speech', 'Connected Speech & Elision (گفتار پیوسته و ادغام)')], max_length=32)),
                ('title_en', models.CharField(max_length=128)),
                ('title_fa', models.CharField(max_length=128)),
                ('target_text', models.CharField(max_length=255)),
                ('ipa', models.CharField(max_length=128)),
                ('stress_pattern', models.CharField(blank=True, default='', max_length=128)),
                ('target_wpm', models.FloatField(default=120.0)),
                ('difficulty_level', models.CharField(default='B1', max_length=16)),
                ('l1_note_en', models.TextField(blank=True, default='')),
                ('l1_note_fa', models.TextField(blank=True, default='')),
                ('example_sentence', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pronunciation Practice Item',
                'verbose_name_plural': 'Pronunciation Practice Items',
                'ordering': ['category', 'difficulty_level', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PronunciationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_text', models.CharField(max_length=255)),
                ('spoken_transcript', models.TextField(blank=True, default='')),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('speech_rate_wpm', models.FloatField(default=0.0)),
                ('pause_count', models.IntegerField(default=0)),
                ('intelligibility_score', models.IntegerField(default=75)),
                ('stress_matched', models.BooleanField(default=True)),
                ('feedback_en', models.TextField(blank=True, default='')),
                ('feedback_fa', models.TextField(blank=True, default='')),
                ('saved_to_genome', models.BooleanField(default=False)),
                ('genome_pattern_key', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_attempts', to=settings.AUTH_USER_MODEL)),
                ('practice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='pronunciation.pronunciationitem')),
            ],
            options={
                'verbose_name': 'Pronunciation Attempt',
                'verbose_name_plural': 'Pronunciation Attempts',
                'ordering': ['-created_at'],
            },
        ),
    ]
