# Generated by Django 5.2.17 on 2026-09-06 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('normalized_title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('content', models.TextField(blank=True, default='', verbose_name='محتوا')),
                ('normalized_content', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(choices=[('course', 'دوره آموزشی'), ('teacher', 'مدرس'), ('community_post', 'پست جامعه'), ('lesson_plan', 'طرح درس'), ('faq', 'سوال متداول'), ('assignment', 'تکلیف اختصاصی'), ('class', 'کلاس')], db_index=True, max_length=32, verbose_name='نوع محتوا')),
                ('visibility', models.CharField(choices=[('public', 'عمومی'), ('authenticated', 'کاربران وارد شده'), ('teacher_only', 'مخصوص مدرسان'), ('student_only', 'مخصوص زبان\u200cآموزان'), ('private_owner', 'مخصوص مالک')], db_index=True, default='public', max_length=32, verbose_name='سطح دسترسی')),
                ('owner_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='شناسه مالک')),
                ('target_id', models.CharField(db_index=True, max_length=128, verbose_name='شناسه هدف')),
                ('target_url', models.CharField(max_length=512, verbose_name='آدرس هدف')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='برچسب\u200cها')),
                ('popularity_score', models.IntegerField(db_index=True, default=0, verbose_name='امتیاز محبوبیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سند جستجو',
                'verbose_name_plural': 'اسناد جستجو',
                'ordering': ['-popularity_score', '-updated_at'],
                'indexes': [models.Index(fields=['content_type', 'visibility'], name='search_sear_content_c1206e_idx'), models.Index(fields=['owner_id', 'visibility'], name='search_sear_owner_i_dc5d27_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=255, verbose_name='عبارت جستجو')),
                ('normalized_query', models.CharField(db_index=True, max_length=255)),
                ('results_count', models.IntegerField(default=0, verbose_name='تعداد نتایج')),
                ('is_zero_result', models.BooleanField(db_index=True, default=False, verbose_name='بدون نتیجه')),
                ('filter_applied', models.CharField(blank=True, default='', max_length=64, verbose_name='فیلتر اعمال شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش جستجو',
                'verbose_name_plural': 'گزارش\u200cهای جستجو',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=255, verbose_name='عبارت جستجو')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_searches', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'جستجوی اخیر',
                'verbose_name_plural': 'جستجوهای اخیر',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'query')},
            },
        ),
    ]
