# Generated by Django 5.2.17 on 2026-09-05 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_id', models.CharField(blank=True, default='', max_length=64)),
                ('prompt_title', models.CharField(blank=True, default='', max_length=255)),
                ('prompt_text', models.TextField(blank=True, default='')),
                ('target_cefr', models.CharField(default='B1', max_length=8)),
                ('mode', models.CharField(choices=[('general', 'General English'), ('ielts_academic', 'IELTS Academic Writing'), ('ielts_general', 'IELTS General Writing'), ('free', 'Free Writing')], default='general', max_length=32)),
                ('text', models.TextField(blank=True, default='')),
                ('word_count', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('analyzed', 'Analyzed'), ('revised', 'Revised')], default='draft', max_length=20)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('is_shared_with_teacher', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_drafts', to=settings.AUTH_USER_MODEL)),
                ('parent_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='writing_mentor.writingdraft')),
            ],
            options={
                'verbose_name': 'Writing Draft',
                'verbose_name_plural': 'Writing Drafts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths_summary_fa', models.TextField(blank=True, default='')),
                ('strengths_summary_en', models.TextField(blank=True, default='')),
                ('top_priorities_fa', models.JSONField(default=list)),
                ('top_priorities_en', models.JSONField(default=list)),
                ('estimated_cefr_range', models.CharField(default='B1 – B2', max_length=32)),
                ('ielts_scores', models.JSONField(default=dict)),
                ('error_annotations', models.JSONField(default=list)),
                ('graduated_rewrites', models.JSONField(default=dict)),
                ('revision_tasks', models.JSONField(default=list)),
                ('disclaimer_fa', models.TextField(default='اصل شفافیت آموزشی (قانون شماره ۸ اساسنامه): نمره و سطح تخمینی برای هدایت فرآیند بازنویسی بوده و مدرک رسمی آزمون آیلتس محسوب نمی\u200cشود.')),
                ('disclaimer_en', models.TextField(default='Product Constitution Rule #8 Disclosure: Estimated band ranges and CEFR levels are formative coaching indicators and do not constitute an official IELTS or CEFR certificate.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='writing_mentor.writingdraft')),
            ],
            options={
                'verbose_name': 'Writing Analysis',
                'verbose_name_plural': 'Writing Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
