# Generated by Django 5.2.17 on 2026-09-05 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('summary_fa', models.TextField(blank=True)),
                ('summary_en', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('listening', 'Listening'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('writing', 'Writing'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('culture', 'Culture & Events'), ('school', 'School & High School (Vision / Konkur)')], db_index=True, max_length=32)),
                ('content_type', models.CharField(choices=[('article', 'Article / Rich Guide'), ('audio_lesson', 'Audio Lesson'), ('video_lesson', 'Video Lesson'), ('culture_post', 'Culture / Event Post'), ('school_guide', 'High School / Konkur Lesson'), ('practice_quiz', 'Formative Practice Quiz')], default='article', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1 Breakthrough'), ('A2', 'A2 Elementary'), ('B1', 'B1 Intermediate'), ('B2', 'B2 Upper-Intermediate'), ('C1', 'C1 Advanced'), ('C2', 'C2 Proficiency'), ('ALL', 'All Levels')], db_index=True, default='B1', max_length=8)),
                ('age_band', models.CharField(choices=[('all', 'All Ages'), ('kids', 'Kids (Under 13)'), ('teens', 'Teens (13-17)'), ('adults', 'Adults (18+)')], default='all', max_length=16)),
                ('school_grade', models.CharField(choices=[('vision_1', 'Vision 1 (10th Grade / پایه دهم)'), ('vision_2', 'Vision 2 (11th Grade / پایه یازدهم)'), ('vision_3', 'Vision 3 (12th Grade / پایه دوازدهم)'), ('konkur', 'Konkur English (کنکور سراسری)'), ('none', 'Not School Specific')], db_index=True, default='none', max_length=32)),
                ('content_body_fa', models.TextField(blank=True, help_text='Persian explanation and pedagogical guidance')),
                ('content_body_en', models.TextField(blank=True, help_text='English text, examples, and dialogues')),
                ('learning_objectives', models.JSONField(blank=True, default=list, help_text='List of pedagogical objectives')),
                ('prerequisites', models.JSONField(blank=True, default=list, help_text='Prerequisite knowledge or slugs')),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('audio_duration_seconds', models.PositiveIntegerField(default=0)),
                ('audio_transcript_fa', models.TextField(blank=True)),
                ('audio_transcript_en', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('video_duration_seconds', models.PositiveIntegerField(default=0)),
                ('video_captions', models.TextField(blank=True, help_text='SRT or VTT formatted captions')),
                ('downloadable_resources', models.JSONField(blank=True, default=list, help_text='List of objects with title_fa, title_en, file_url, file_size_bytes, file_type')),
                ('quiz_data', models.JSONField(blank=True, default=list, help_text='List of quiz items with prompt_fa, prompt_en, options, correct_index, explanation_fa, explanation_en')),
                ('is_premium', models.BooleanField(default=False, help_text='Requires active subscription if True')),
                ('free_preview_excerpt_fa', models.TextField(blank=True, help_text='Public teaser/preview in Persian')),
                ('free_preview_excerpt_en', models.TextField(blank=True, help_text='Public teaser/preview in English')),
                ('source_attribution', models.CharField(help_text='Author/Source attribution', max_length=255)),
                ('license_type', models.CharField(choices=[('original_editorial', 'Original Editorial (Endoora)'), ('cc_by_sa', 'Creative Commons Attribution-ShareAlike'), ('public_domain', 'Public Domain'), ('educational_fair_use', 'Educational Fair Use')], default='original_editorial', max_length=32)),
                ('author_name', models.CharField(default='Endoora Editorial Team', max_length=128)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Item',
                'verbose_name_plural': 'Content Items',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentReviewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], max_length=16)),
                ('new_status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], max_length=16)),
                ('editorial_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='content.contentitem')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
