# Generated by Django 5.2.17 on 2026-09-05 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_accent', models.CharField(choices=[('US', 'American English'), ('UK', 'British English'), ('AU', 'Australian English')], default='US', max_length=16)),
                ('playback_speed', models.FloatField(default=1.0)),
                ('default_retention', models.CharField(choices=[('immediate', 'Auto-delete immediately after transcription'), ('7_days', 'Retain for 7 days'), ('30_days', 'Retain for 30 days'), ('keep', 'Retain indefinitely')], default='immediate', max_length=20)),
                ('auto_play_tts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=100)),
                ('scenario_id', models.CharField(blank=True, default='', max_length=64)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice_recordings/%Y/%m/%d/')),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('mime_type', models.CharField(default='audio/webm', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transcribed', 'Transcribed'), ('failed', 'Failed'), ('deleted', 'Audio Deleted')], default='pending', max_length=20)),
                ('stt_transcript', models.TextField(blank=True, default='')),
                ('corrected_transcript', models.TextField(blank=True, default='')),
                ('retention_policy', models.CharField(choices=[('immediate', 'Auto-delete immediately after transcription'), ('7_days', 'Retain for 7 days'), ('30_days', 'Retain for 30 days'), ('keep', 'Retain indefinitely')], default='immediate', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Recording',
                'verbose_name_plural': 'Voice Recordings',
                'ordering': ['-created_at'],
            },
        ),
    ]
