# Generated by Django 5.2.17 on 2026-09-05 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='openrouter_main', max_length=100, unique=True)),
                ('provider', models.CharField(default='openrouter', max_length=50)),
                ('api_base_url', models.CharField(default='https://openrouter.ai/api/v1', max_length=255)),
                ('api_key_env_var', models.CharField(default='ENDOORA_OPENROUTER_API_KEY', max_length=100)),
                ('timeout_seconds', models.PositiveIntegerField(default=15, help_text='Circuit breaker timeout in seconds')),
                ('daily_budget_usd', models.FloatField(default=5.0, help_text='Daily budget cap to prevent runaway billing')),
                ('current_daily_spend_usd', models.FloatField(default=0.0)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(default='exercise_generation', max_length=100)),
                ('prompt_id', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=20)),
                ('model_name', models.CharField(max_length=200)),
                ('provider', models.CharField(default='openrouter', max_length=50)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_cost_usd', models.FloatField(default=0.0)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('is_fallback', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feature', 'created_at'], name='ai_gateway__feature_8a4043_idx'), models.Index(fields=['success', 'is_fallback'], name='ai_gateway__success_a43818_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneratedExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('target_skill', models.CharField(default='grammar', max_length=50)),
                ('cefr_level', models.CharField(default='B1', max_length=10)),
                ('objective_id', models.CharField(blank=True, max_length=120)),
                ('questions', models.JSONField(default=list, help_text='Validated structured question items with prompt, options, answer key, and explanation')),
                ('is_fallback', models.BooleanField(default=False, help_text='True if generated from reviewed question bank fallback')),
                ('model_used', models.CharField(default='reviewed_bank_fallback', max_length=200)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, help_text='Map of question_id -> selected_option_id')),
                ('score_percentage', models.FloatField(default=0.0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL)),
                ('exercise_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ai_gateway.generatedexerciseset')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='generatedexerciseset',
            index=models.Index(fields=['learner', 'target_skill'], name='ai_gateway__learner_57cb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedexerciseset',
            index=models.Index(fields=['learner', 'created_at'], name='ai_gateway__learner_ac36d6_idx'),
        ),
    ]
