# Generated by Django 5.2.17 on 2026-09-05 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('level_title_fa', models.CharField(default='کاوشگر نوآموز', max_length=128)),
                ('level_title_en', models.CharField(default='Novice Explorer', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learner Level',
                'verbose_name_plural': 'Learner Levels',
            },
        ),
        migrations.CreateModel(
            name='LearnerStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('freeze_credits', models.PositiveIntegerField(default=1, help_text='Grace freeze protections available to protect against accidental streak breakage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learner Streak',
                'verbose_name_plural': 'Learner Streaks',
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Points awarded (positive) or reversal (negative)')),
                ('category', models.CharField(choices=[('mission', 'Daily Mission Step'), ('roleplay', 'Roleplay Scenario Completion'), ('srs', 'SRS Vocabulary Review'), ('pronunciation', 'Pronunciation Lab Practice'), ('writing', 'Writing Mentor Submission'), ('placement', 'Placement Diagnostic Section'), ('streak_bonus', 'Streak Consistency Reward'), ('system_adjustment', 'Compensatory Adjustment')], default='mission', max_length=64)),
                ('reason', models.CharField(max_length=255)),
                ('source_event', models.CharField(db_index=True, help_text='Unique event idempotency key e.g. mission:2026-09-05:step:2:user:1', max_length=255, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'XP Transaction',
                'verbose_name_plural': 'XP Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
