# Generated by Django 5.2.17 on 2026-09-05 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUsersClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name_fa', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
                ('description_fa', models.TextField()),
                ('description_en', models.TextField()),
                ('badge_icon', models.CharField(default='🌟', max_length=32)),
                ('tier', models.CharField(choices=[('apprentice', 'Apprentice Club'), ('scholar', 'Scholar Club'), ('master', 'Master Communicator Club')], default='apprentice', max_length=32)),
                ('min_active_days_7d', models.PositiveIntegerField(default=2)),
                ('min_xp_7d', models.PositiveIntegerField(default=100)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Active Users Club',
                'verbose_name_plural': 'Active Users Clubs',
                'ordering': ['min_active_days_7d', 'min_xp_7d'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title_fa', models.CharField(max_length=128)),
                ('title_en', models.CharField(max_length=128)),
                ('description_fa', models.TextField()),
                ('description_en', models.TextField()),
                ('icon', models.CharField(default='🏅', max_length=32)),
                ('category', models.CharField(choices=[('firsts', 'Meaningful Firsts'), ('consistency', 'Consistency & Habits'), ('skills', 'Skill Mastery'), ('community', 'Community & Clubs')], default='firsts', max_length=32)),
                ('xp_reward', models.PositiveIntegerField(default=100)),
                ('criteria_type', models.CharField(help_text='Metric type e.g. placement_complete, streak_days, srs_cards, writing_submit, roleplay_complete, seven_day_sprint', max_length=64)),
                ('criteria_threshold', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['category', 'criteria_threshold', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('challenge_type', models.CharField(choices=[('daily', 'Daily Challenge'), ('weekly', 'Weekly Challenge'), ('seven_day_sprint', '7-Day Consistency Sprint')], default='daily', max_length=32)),
                ('title_fa', models.CharField(max_length=128)),
                ('title_en', models.CharField(max_length=128)),
                ('description_fa', models.TextField()),
                ('description_en', models.TextField()),
                ('icon', models.CharField(default='🎯', max_length=32)),
                ('target_metric', models.CharField(help_text='Target metric e.g. srs_reviews, pronunciation_exercises, roleplay_complete, writing_submit, active_days, consecutive_days', max_length=64)),
                ('target_count', models.PositiveIntegerField(default=1)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Challenge Template',
                'verbose_name_plural': 'Challenge Templates',
                'ordering': ['challenge_type', 'target_count', 'slug'],
            },
        ),
        migrations.AlterField(
            model_name='xptransaction',
            name='category',
            field=models.CharField(choices=[('mission', 'Daily Mission Step'), ('roleplay', 'Roleplay Scenario Completion'), ('srs', 'SRS Vocabulary Review'), ('pronunciation', 'Pronunciation Lab Practice'), ('writing', 'Writing Mentor Submission'), ('placement', 'Placement Diagnostic Section'), ('streak_bonus', 'Streak Consistency Reward'), ('challenge', 'Challenge Completion Reward'), ('badge_unlock', 'Badge Achievement Reward'), ('system_adjustment', 'Compensatory Adjustment')], default='mission', max_length=64),
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('board_type', models.CharField(choices=[('global', 'Global Cohort'), ('city', 'City Cohort'), ('club', 'Club Cohort')], default='global', max_length=32)),
                ('city_name', models.CharField(blank=True, max_length=64, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('is_suppressed', models.BooleanField(default=False, help_text='True if cohort size is below minimum safe threshold (10 learners) to protect privacy.')),
                ('suppression_reason', models.CharField(blank=True, max_length=255)),
                ('total_eligible', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='gamification.activeusersclub')),
            ],
            options={
                'verbose_name': 'Leaderboard Snapshot',
                'verbose_name_plural': 'Leaderboard Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearnerPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leaderboard_visible', models.BooleanField(default=True, help_text='Opt-in visibility toggle. If False, learner never appears on any public/cohort leaderboard.')),
                ('pseudonym', models.CharField(blank=True, help_text="Pseudonym handle e.g. 'Learner #4821' or 'PhoenixScholar'. Real name never exposed.", max_length=64)),
                ('city', models.CharField(blank=True, help_text='City location for optional city-level cohort comparison.', max_length=64)),
                ('show_city_rank', models.BooleanField(default=False, help_text='Consent to appear on city-level cohort leaderboard when cohort is safely large.')),
                ('is_minor', models.BooleanField(default=False, help_text='Under-18 safeguard: strictly suppresses city location and forbids city leaderboard presence.')),
                ('avatar_seed', models.CharField(default='avatar-1', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_privacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learner Privacy Settings',
                'verbose_name_plural': 'Learner Privacy Settings',
            },
        ),
        migrations.CreateModel(
            name='SevenDaySprintEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Sprint start date in Asia/Tehran')),
                ('end_date', models.DateField(help_text='Sprint end date in Asia/Tehran')),
                ('days_completed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_enrollments', to=settings.AUTH_USER_MODEL)),
                ('reward_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_award', to='gamification.xptransaction')),
            ],
            options={
                'verbose_name': '7-Day Sprint Enrollment',
                'verbose_name_plural': '7-Day Sprint Enrollments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reported_count', models.PositiveIntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gamification.activeusersclub')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Club Membership',
                'verbose_name_plural': 'Club Memberships',
                'ordering': ['-joined_at'],
                'unique_together': {('learner', 'club')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('total_xp', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField(default=1)),
                ('display_name', models.CharField(help_text='Pseudonym display name only; never real name or phone', max_length=64)),
                ('avatar_seed', models.CharField(default='avatar-1', max_length=32)),
                ('tiebreaker_achieved_at', models.DateTimeField()),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='gamification.leaderboardsnapshot')),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard Entries',
                'ordering': ['rank'],
                'unique_together': {('snapshot', 'learner')},
            },
        ),
        migrations.CreateModel(
            name='LearnerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('source_event', models.CharField(db_index=True, help_text='Unique event idempotency key e.g. badge:streak-3:user:1', max_length=255, unique=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_learners', to='gamification.badge')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_badges', to=settings.AUTH_USER_MODEL)),
                ('xp_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_award', to='gamification.xptransaction')),
            ],
            options={
                'verbose_name': 'Learner Badge',
                'verbose_name_plural': 'Learner Badges',
                'ordering': ['-unlocked_at'],
                'unique_together': {('learner', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='LearnerChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='Period start in Asia/Tehran')),
                ('period_end', models.DateField(help_text='Period end in Asia/Tehran')),
                ('current_progress', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_challenges', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_instances', to='gamification.challengetemplate')),
                ('xp_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_award', to='gamification.xptransaction')),
            ],
            options={
                'verbose_name': 'Learner Challenge',
                'verbose_name_plural': 'Learner Challenges',
                'ordering': ['-period_start'],
                'unique_together': {('learner', 'template', 'period_start')},
            },
        ),
    ]
