# Generated by Django 5.2.17 on 2026-09-05 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('description_fa', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('skill_category', models.CharField(choices=[('listening', 'Listening'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('writing', 'Writing'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('culture', 'Culture & Events'), ('school', 'School & High School (Vision / Konkur)')], db_index=True, max_length=32)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1 Breakthrough'), ('A2', 'A2 Elementary'), ('B1', 'B1 Intermediate'), ('B2', 'B2 Upper-Intermediate'), ('C1', 'C1 Advanced'), ('C2', 'C2 Proficiency'), ('ALL', 'All Levels')], db_index=True, default='B1', max_length=8)),
                ('target_audience', models.CharField(choices=[('general', 'General English Learners'), ('school_konkur', 'Iranian High School & Konkur'), ('ielts_academic', 'IELTS & Academic Prep'), ('business', 'Business & Career English')], db_index=True, default='general', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('is_premium', models.BooleanField(default=True, help_text='Premium course requiring subscription entitlement')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('estimated_hours', models.PositiveIntegerField(default=10)),
                ('source_attribution', models.CharField(default='Endoora Curriculum Team', max_length=255)),
                ('license_type', models.CharField(choices=[('original_editorial', 'Original Editorial (Endoora)'), ('cc_by_sa', 'Creative Commons Attribution-ShareAlike'), ('public_domain', 'Public Domain'), ('educational_fair_use', 'Educational Fair Use')], default='original_editorial', max_length=32)),
                ('author_name', models.CharField(default='Endoora Academic Board', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('description_fa', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('is_free_preview', models.BooleanField(default=False, help_text='If True, accessible even without premium entitlement')),
                ('content_body_fa', models.TextField(blank=True)),
                ('content_body_en', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('transcript_fa', models.TextField(blank=True)),
                ('transcript_en', models.TextField(blank=True)),
                ('quiz_data', models.JSONField(blank=True, default=list)),
                ('downloadable_resources', models.JSONField(blank=True, default=list)),
                ('free_preview_excerpt_fa', models.TextField(blank=True)),
                ('free_preview_excerpt_en', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('module', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LearnerCourseEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('learner', 'course')},
            },
        ),
        migrations.CreateModel(
            name='LearnerLessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('quiz_score', models.FloatField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_completions', to='courses.lesson')),
            ],
            options={
                'unique_together': {('learner', 'lesson')},
            },
        ),
    ]
