# Generated by Django 5.2.17 on 2026-09-15 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_phone', models.CharField(max_length=32)),
                ('template_name', models.CharField(default='general_notice', max_length=64)),
                ('pattern_tokens', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(default='Kavenegar', max_length=64)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=64)),
                ('delivery_status', models.CharField(default='DELIVERED', max_length=24)),
                ('cost_rials', models.IntegerField(default=1200)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-dispatched_at',),
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('learning_updates', models.BooleanField(default=True)),
                ('assignment_alerts', models.BooleanField(default=True)),
                ('financial_receipts', models.BooleanField(default=True)),
                ('security_warnings', models.BooleanField(default=True)),
                ('marketing_promotions', models.BooleanField(default=False)),
                ('phone_number_verified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('LEARNING', 'یادگیری و تمارین'), ('ASSIGNMENT', 'تکالیف و آزمون\u200cها'), ('SECURITY', 'امنیت و حساب کاربری'), ('FINANCIAL', 'تراکنش\u200cهای مالی و کیف پول'), ('SYSTEM', 'اطلاعیه\u200cهای سیستم')], default='SYSTEM', max_length=24)),
                ('channel', models.CharField(choices=[('IN_APP', 'درون\u200cبرنامه\u200cای'), ('SMS', 'پیامک ایران'), ('EMAIL', 'ایمیل')], default='IN_APP', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('SENT', 'ارسال شده'), ('DELIVERED', 'تحویل شده'), ('READ', 'خوانده شده'), ('FAILED', 'ناموفق')], default='DELIVERED', max_length=16)),
                ('action_url', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'status', '-created_at'], name='notificatio_recipie_1b3d03_idx')],
            },
        ),
    ]
