# Generated by Django 5.2.17 on 2026-09-06 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=128)),
                ('author_role', models.CharField(default='learner', max_length=32)),
                ('is_verified_teacher', models.BooleanField(default=False, help_text='Teacher verification badge verified by platform credentials')),
                ('post_type', models.CharField(choices=[('learner_post', 'Learner Post'), ('teacher_experience', 'Teacher Experience'), ('lesson_plan', 'Lesson Plan & Pedagogical Resource'), ('question', 'Question & Help'), ('resource', 'Community Resource')], db_index=True, default='learner_post', max_length=32)),
                ('audience', models.CharField(choices=[('all', 'All Community'), ('learners', 'Learners Only'), ('teachers', 'Teachers Only')], db_index=True, default='all', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('hidden', 'Hidden'), ('removed', 'Removed by Moderation')], db_index=True, default='published', max_length=16)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('content_fa', models.TextField(help_text='Main content in Persian')),
                ('content_en', models.TextField(blank=True, help_text='English text or translation')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('media_attachments', models.JSONField(blank=True, default=list, help_text='Media attachments with mandatory alt_text and caption')),
                ('lesson_plan_metadata', models.JSONField(blank=True, default=dict, help_text='Lesson plan metadata: license_type, copyright_attribution, file_url, file_format, grade_level')),
                ('is_monthly_featured', models.BooleanField(db_index=True, default=False)),
                ('featured_at', models.DateTimeField(blank=True, null=True)),
                ('editorial_review_notes', models.TextField(blank=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('reactions_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('is_suitable_for_minors', models.BooleanField(default=True, help_text='True if suitable for all learners including minors')),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
                ('featured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Post',
                'verbose_name_plural': 'Community Posts',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('hidden', 'Hidden'), ('removed', 'Removed by Moderation')], db_index=True, default='published', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.postcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.communitypost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('like', 'مفید و لایک'), ('helpful', 'راهگشا و کاربردی'), ('inspiring', 'الهام\u200cبخش'), ('insightful', 'عمیق و نکته\u200cآموز')], default='like', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user', 'reaction_type')},
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_mute_only', models.BooleanField(default=False, help_text='True if muted rather than fully blocked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('blocker', 'blocked_user')},
            },
        ),
    ]
