# Generated by Django 5.2.17 on 2026-08-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITextInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('prompt_type', models.CharField(max_length=64)),
                ('learner_input', models.TextField()),
                ('ai_output', models.TextField()),
                ('limitation_notice', models.TextField(default='AI feedback is educational support, not a certified assessment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('section', models.CharField(default='listening', max_length=32)),
                ('audio_asset_id', models.UUIDField(blank=True, null=True)),
                ('transcript_version', models.CharField(default='v1', max_length=64)),
                ('response', models.JSONField(default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
