# Generated by Django 5.2.17 on 2026-09-15 18:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name_fa', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
                ('description_fa', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('onboarding', 'User Onboarding & Signup'), ('placement', 'Placement & Activation'), ('monetization', 'Teacher Booking & Commerce'), ('retention', 'Daily Learning Retention')], default='onboarding', max_length=32)),
                ('steps', models.JSONField(default=list, help_text='Ordered list of step definitions with event_name, name_fa, name_en, step_index')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='DailyAnalyticsRollup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('metric_type', models.CharField(choices=[('dau', 'Daily Active Users'), ('wau', 'Weekly Active Users'), ('mau', 'Monthly Active Users'), ('stickiness', 'DAU/MAU Stickiness Ratio'), ('total_events', 'Total Telemetry Events'), ('retention_d1', 'Day 1 Retention'), ('retention_d7', 'Day 7 Retention'), ('retention_d14', 'Day 14 Retention'), ('retention_d30', 'Day 30 Retention')], db_index=True, max_length=32)),
                ('dimension', models.CharField(db_index=True, default='all', max_length=64)),
                ('value', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-date', 'metric_type'),
                'unique_together': {('date', 'metric_type', 'dimension')},
            },
        ),
        migrations.CreateModel(
            name='ProductAnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(choices=[('auth', 'Authentication & Identity'), ('onboarding', 'Onboarding & Role Choice'), ('placement', 'Diagnostic & Placement'), ('learning', 'Daily Missions & SRS'), ('teacher', 'Teacher Workspace & Marketplace'), ('commerce', 'Checkout & Financial'), ('route', 'Route Views & Navigation')], db_index=True, default='route', max_length=32)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('client_ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent_category', models.CharField(choices=[('desktop', 'Desktop Browser'), ('mobile', 'Mobile Device'), ('tablet', 'Tablet Device'), ('bot', 'Search Bot / Crawler'), ('unknown', 'Unknown Device')], default='desktop', max_length=16)),
                ('locale', models.CharField(default='fa', max_length=8)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_name', 'created_at'], name='analytics_p_event_n_8267fb_idx'), models.Index(fields=['category', 'created_at'], name='analytics_p_categor_ab807c_idx'), models.Index(fields=['user', 'created_at'], name='analytics_p_user_id_886766_idx')],
            },
        ),
    ]
