# Generated by Django 5.2.17 on 2026-09-06 18:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان کلاس')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('subject', models.CharField(max_length=128, verbose_name='موضوع و مهارت اصلی')),
                ('level', models.CharField(default='B1', max_length=16, verbose_name='سطح زبانی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('archived', 'بایگانی شده'), ('completed', 'تکمیل شده')], db_index=True, default='active', max_length=32, verbose_name='وضعیت کلاس')),
                ('max_capacity', models.PositiveIntegerField(default=1, verbose_name='ظرفیت حداکثر')),
                ('objectives', models.JSONField(blank=True, default=list, verbose_name='اهداف آموزشی')),
                ('private_notes', models.TextField(blank=True, default='', verbose_name='یادداشت\u200cهای اختصاصی مدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_classes', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'کلاس مدیریت شده مدرس',
                'verbose_name_plural': 'کلاس\u200cهای مدیریت شده مدرس',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان جلسه')),
                ('scheduled_start', models.DateTimeField(verbose_name='زمان شروع برنامه\u200cریزی شده')),
                ('scheduled_end', models.DateTimeField(verbose_name='زمان پایان برنامه\u200cریزی شده')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='مدت جلسه (دقیقه)')),
                ('status', models.CharField(choices=[('scheduled', 'برنامه\u200cریزی شده'), ('completed', 'برگزار شده'), ('cancelled', 'لغو شده')], db_index=True, default='scheduled', max_length=32, verbose_name='وضعیت جلسه')),
                ('session_notes', models.TextField(blank=True, default='', verbose_name='خلاصه و یادداشت جلسه')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان واقعی پایان')),
                ('confirmed_by_teacher', models.BooleanField(default=False, verbose_name='تایید مدرس')),
                ('confirmed_by_learner', models.BooleanField(default=False, verbose_name='تایید زبان\u200cآموز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_sessions', to=settings.AUTH_USER_MODEL, verbose_name='زبان\u200cآموز')),
                ('teacher_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='teachers.teacherclass', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'جلسه کلاسی',
                'verbose_name_plural': 'جلسات کلاسی',
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='TeacherDataAccessAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_type', models.CharField(max_length=64, verbose_name='نوع دسترسی به داده')),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_access_records', to=settings.AUTH_USER_MODEL, verbose_name='زبان\u200cآموز')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_access_actions', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'گزارش دسترسی به داده\u200cهای آموزشی',
                'verbose_name_plural': 'گزارش\u200cهای دسترسی به داده\u200cهای آموزشی',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TeachingHourLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='ساعت تدریس')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('disputed', 'مورد اختلاف'), ('revised', 'اصلاح شده')], db_index=True, default='confirmed', max_length=32, verbose_name='وضعیت تایید')),
                ('is_verified', models.BooleanField(default=True, verbose_name='تایید شده برای ثبت مالی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entry', to='teachers.classsession', verbose_name='جلسه تایید شده')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_hour_ledgers', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'ثبت ساعت تدریس',
                'verbose_name_plural': 'دفتر ساعات تدریس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeachingHourAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=32, verbose_name='نوع تغییر')),
                ('previous_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(verbose_name='علت و مستندات تغییر')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر اقدام\u200cکننده')),
                ('ledger_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='teachers.teachinghourledger', verbose_name='رکورد ساعت تدریس')),
            ],
            options={
                'verbose_name': 'گزارش حسابرسی ساعت تدریس',
                'verbose_name_plural': 'گزارش\u200cهای حسابرسی ساعت تدریس',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TeacherLearnerLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_consent', 'در انتظار تایید زبان\u200cآموز'), ('active', 'فعال و متصل'), ('terminated', 'خاتمه یافته'), ('rejected', 'رد شده')], db_index=True, default='pending_consent', max_length=32, verbose_name='وضعیت پیوند')),
                ('invite_code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='کد دعوت')),
                ('consent_given_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان اعطای رضایت')),
                ('terminated_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خاتمه ارتباط')),
                ('termination_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='علت خاتمه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_links', to=settings.AUTH_USER_MODEL, verbose_name='زبان\u200cآموز')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_links', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
                ('teacher_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='teachers.teacherclass', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'پیوند آموزشی مدرس و زبان\u200cآموز',
                'verbose_name_plural': 'پیوندهای آموزشی مدرس و زبان\u200cآموز',
                'ordering': ['-updated_at'],
                'unique_together': {('teacher_class', 'learner')},
            },
        ),
    ]
