# Generated by Django 5.2.17 on 2026-09-06 19:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان تکلیف/تمرین')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('instructions', models.TextField(blank=True, default='', verbose_name='دستورالعمل آزمون/تکلیف')),
                ('target_cefr', models.CharField(default='B1', max_length=16, verbose_name='سطح هدف CEFR')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('closed', 'پایان یافته'), ('archived', 'بایگانی شده')], db_index=True, default='draft', max_length=32, verbose_name='وضعیت')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='مهلت ارسال (ددلاین)')),
                ('grace_period_minutes', models.PositiveIntegerField(default=0, help_text='مدت زمان ارفاقی پس از ددلاین قبل از بسته شدن امکان ثبت', verbose_name='فرصت ارفاقی (دقیقه)')),
                ('allow_late_submission', models.BooleanField(default=False, help_text='آیا پس از مهلت، ارسال به عنوان با تاخیر مجاز است', verbose_name='امکان ارسال با تاخیر')),
                ('max_attempts', models.PositiveIntegerField(default=1, help_text='تعداد مجاز بار شرکت در آزمون/تکلیف', verbose_name='حداکثر دفعات تلاش')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='مدت زمان مجاز برای هر تلاش؛ خالی برای بدون محدودیت', null=True, verbose_name='محدودیت زمانی (دقیقه)')),
                ('total_points', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6, verbose_name='مجموع نمره')),
                ('passing_percentage', models.PositiveIntegerField(default=60, verbose_name='درصد قبولی')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='نسخه ویرایش (کنترل همزمانی)')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
                ('teacher_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.teacherclass', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'تکلیف کلاسی',
                'verbose_name_plural': 'تکالیف کلاسی',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentAccommodation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extra_time_minutes', models.PositiveIntegerField(default=0, verbose_name='زمان اضافه ارفاقی (دقیقه)')),
                ('extra_attempts', models.PositiveIntegerField(default=0, verbose_name='دفعات تلاش اضافه')),
                ('extended_due_date', models.DateTimeField(blank=True, null=True, verbose_name='ددلاین تمدید شده اختصاصی')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت و علت انطباق آموزشی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='teachers.assignment', verbose_name='تکلیف')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_accommodations', to=settings.AUTH_USER_MODEL, verbose_name='زبان\u200cآموز')),
            ],
            options={
                'verbose_name': 'انطباق و تسهیلات آموزشی تکلیف',
                'verbose_name_plural': 'تسهیلات و انطباقات آموزشی تکالیف',
                'ordering': ['-updated_at'],
                'unique_together': {('assignment', 'learner')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='شماره تلاش')),
                ('status', models.CharField(choices=[('in_progress', 'در حال انجام'), ('submitted', 'ارسال شده'), ('graded', 'تصحیح شده'), ('timed_out', 'مهلت تمام شده')], db_index=True, default='in_progress', max_length=32, verbose_name='وضعیت تلاش')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('time_limit_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='مهلت پایان تایمر این تلاش')),
                ('answers_payload', models.JSONField(blank=True, default=dict, help_text='ذخیره خودکار پیش\u200cنویس پاسخ\u200cها بر اساس شناسه نسخه سوال', verbose_name='پاسخ\u200cهای زبان\u200cآموز')),
                ('grading_results', models.JSONField(blank=True, default=dict, verbose_name='نتیجه تصحیح آزمون')),
                ('score_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='نمره کسب شده')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درصد نمره')),
                ('is_late', models.BooleanField(default=False, verbose_name='ثبت با تاخیر')),
                ('teacher_feedback', models.TextField(blank=True, default='', verbose_name='بازخورد کیفی مدرس')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تصحیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='teachers.assignment', verbose_name='تکلیف')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assignment_attempts', to=settings.AUTH_USER_MODEL, verbose_name='مصحح')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_attempts', to=settings.AUTH_USER_MODEL, verbose_name='زبان\u200cآموز')),
            ],
            options={
                'verbose_name': 'تلاش زبان\u200cآموز در تکلیف',
                'verbose_name_plural': 'تلاش\u200cهای زبان\u200cآموزان در تکالیف',
                'ordering': ['-started_at'],
                'unique_together': {('assignment', 'learner', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('custom_instructions', models.TextField(blank=True, default='', verbose_name='دستورالعمل سفارشی مدرس')),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='نمره این سوال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_questions', to='teachers.assignment', verbose_name='تکلیف')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_usages', to='questions.questionversion', verbose_name='نسخه سوال بانک سوالات')),
            ],
            options={
                'verbose_name': 'سوال اختصاص داده شده به تکلیف',
                'verbose_name_plural': 'سوالات اختصاص داده شده به تکالیف',
                'ordering': ['order', 'created_at'],
                'unique_together': {('assignment', 'question_version')},
            },
        ),
    ]
