# Generated by Django 5.2.17 on 2026-09-06 21:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentattempt',
            name='feedback_status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی مدرس'), ('returned', 'تصحیح شده و ارسال بازخورد'), ('acknowledged', 'مشاهده و تایید شده توسط زبان\u200cآموز'), ('revision_requested', 'درخواست بازنگری و اصلاح')], db_index=True, default='pending', max_length=32, verbose_name='وضعیت بازخورد'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='learner_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید بازخورد توسط زبان\u200cآموز'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='learner_reflection',
            field=models.TextField(blank=True, default='', verbose_name='یادداشت و خودبازتابی زبان\u200cآموز'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='question_grades',
            field=models.JSONField(blank=True, default=dict, verbose_name='نمرات و بازخوردهای تفکیکی هر سوال'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='revision_notes',
            field=models.TextField(blank=True, default='', verbose_name='دستورالعمل بازنگری و اصلاح'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='rubric_scores',
            field=models.JSONField(blank=True, default=dict, verbose_name='نمرات و معیارهای ارزیابی روبریم'),
        ),
        migrations.AlterField(
            model_name='assignmentattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'در حال انجام'), ('submitted', 'ارسال شده'), ('graded', 'تصحیح شده'), ('timed_out', 'مهلت تمام شده'), ('revision_requested', 'درخواست بازنگری')], db_index=True, default='in_progress', max_length=32, verbose_name='وضعیت تلاش'),
        ),
        migrations.CreateModel(
            name='SubmissionFeedbackMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='متن پیام یا بازخورد')),
                ('is_internal_note', models.BooleanField(default=False, help_text='فقط برای مدرسین قابل مشاهده است و به زبان\u200cآموز نشان داده نمی\u200cشود', verbose_name='یادداشت خصوصی مدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_messages', to='teachers.assignmentattempt', verbose_name='تلاش تکلیف')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_feedback_messages', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده پیام')),
            ],
            options={
                'verbose_name': 'پیام حلقه بازخورد تکلیف',
                'verbose_name_plural': 'پیام\u200cهای حلقه بازخورد تکالیف',
                'ordering': ['created_at'],
            },
        ),
    ]
