# Generated by Django 5.2.17 on 2026-09-09 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_gradebook_and_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtRiskAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('performance_drop', 'افت ناگهانی عملکرد و نمره'), ('low_mastery', 'تسلط ضعیف بر مفاهیم و نمره زیر حد نصاب'), ('missing_assignments', 'تکالیف معوق و عدم ارسال پاسخ'), ('attendance_drop', 'غیبت در جلسات یا عدم تایید حضور'), ('unaddressed_feedback', 'بازخورد و بازنگری بی\u200cپاسخ مانده'), ('manual_flag', 'ثبت نشانه\u200cگذاری دستی توسط مدرس')], db_index=True, max_length=32, verbose_name='نوع هشدار')),
                ('severity', models.CharField(choices=[('high', 'بحرانی و نیازمند اقدام فوری'), ('medium', 'متوسط و هشدار روند نزولی'), ('low', 'پایین و قابل پایش')], db_index=True, default='medium', max_length=16, verbose_name='شدت هشدار')),
                ('status', models.CharField(choices=[('active', 'فعال و نیازمند بررسی'), ('acknowledged', 'مشاهده شده توسط مدرس'), ('resolved', 'حل شده با بهبود یا مداخله'), ('dismissed', 'نادیده گرفته شده')], db_index=True, default='active', max_length=32, verbose_name='وضعیت هشدار')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان هشدار')),
                ('description', models.TextField(verbose_name='شرح دقیق و علت هشدار')),
                ('metrics_snapshot', models.JSONField(blank=True, default=dict, verbose_name='شاخص\u200cهای محرک هشدار')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان مشاهده و تایید مدرس')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان رفع هشدار')),
                ('resolution_notes', models.TextField(blank=True, default='', verbose_name='یادداشت نحوه برطرف\u200cسازی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_at_risk_alerts', to=settings.AUTH_USER_MODEL, verbose_name='زبان\u200cآموز')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_at_risk_alerts', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
                ('teacher_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_risk_alerts', to='teachers.teacherclass', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'هشدار در معرض خطر زبان\u200cآموز',
                'verbose_name_plural': 'هشدارهای در معرض خطر زبان\u200cآموزان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherIntervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intervention_type', models.CharField(choices=[('extra_time_accommodation', 'تسهیلات زمان یا فرصت مجدد'), ('targeted_remedial_assignment', 'تمرین و تکلیف جبرانی هدفمند'), ('one_on_one_office_hour', 'جلسه رفع اشکال و مشاوره اختصاصی'), ('direct_encouragement_note', 'پیام انگیزشی و راهنمای یادگیری مستقیم'), ('learning_plan_adjustment', 'تعدیل برنامه و سرعت یادگیری'), ('other', 'سایر اقدامات حمایتی آموزشی')], db_index=True, max_length=32, verbose_name='نوع مداخله آموزشی')),
                ('status', models.CharField(choices=[('planned', 'برنامه\u200cریزی شده'), ('in_progress', 'در حال اجرا'), ('completed', 'تکمیل شده و ارزیابی نتیجه'), ('cancelled', 'لغو شده')], db_index=True, default='planned', max_length=32, verbose_name='وضعیت اقدام')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مداخله')),
                ('description', models.TextField(verbose_name='شرح اقدام و استراتژی آموزشی')),
                ('action_data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای مرتبط با اقدام')),
                ('outcome_notes', models.TextField(blank=True, default='', verbose_name='ارزیابی نتیجه مداخله')),
                ('score_before', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره یا درصد قبل از اقدام')),
                ('score_after', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره یا درصد پس از اقدام')),
                ('target_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ هدف برای پیگیری')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل مداخله')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='teachers.atriskalert', verbose_name='هشدار مرتبط')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interventions', to=settings.AUTH_USER_MODEL, verbose_name='زبان\u200cآموز هدف')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_interventions', to=settings.AUTH_USER_MODEL, verbose_name='مدرس اقدام\u200cکننده')),
                ('teacher_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='teachers.teacherclass', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'مداخله آموزشی مدرس',
                'verbose_name_plural': 'مداخلات آموزشی مدرسین',
                'ordering': ['-created_at'],
            },
        ),
    ]
