# Generated by Django 5.2.17 on 2026-09-16 06:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_analytics_and_interventions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('success', 'بسیار موفق'), ('partial', 'موفق با چالش جزئی'), ('needs_repeat', 'نیازمند تکرار و تمرین بیشتر')], default='success', max_length=32, verbose_name='نتیجه تدریس')),
                ('difficulty_rating', models.PositiveSmallIntegerField(default=3, verbose_name='درجه سختی (۱ تا ۵)')),
                ('completion_percent', models.PositiveSmallIntegerField(default=100, verbose_name='درصد پوشش مباحث')),
                ('summary', models.TextField(blank=True, default='', verbose_name='خلاصه دستاوردها')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت و مشاهدات معلم')),
                ('followup_reminders', models.JSONField(blank=True, default=list, verbose_name='موارد پیگیری جلسه آینده')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcomes', to='teachers.classsession', verbose_name='جلسه مرتبط')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_outcomes', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
                ('teacher_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_outcomes', to='teachers.teacherclass', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'ثبت نتیجه تدریس جلسه',
                'verbose_name_plural': 'نتایج تدریس جلسات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpacedReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_item', models.CharField(max_length=255, verbose_name='واژه یا نکته گرامری')),
                ('item_type', models.CharField(default='vocabulary', max_length=32, verbose_name='نوع آیتم')),
                ('prompt_question', models.TextField(blank=True, default='', verbose_name='سوال مرور یا فلش\u200cکارت')),
                ('correct_answer', models.TextField(blank=True, default='', verbose_name='پاسخ صحیح')),
                ('due_date', models.DateField(db_index=True, verbose_name='تاریخ موعد مرور بعدی')),
                ('interval_days', models.PositiveIntegerField(default=1, verbose_name='فاصله مرور (روز)')),
                ('repetition_count', models.PositiveIntegerField(default=0, verbose_name='تعداد مرور موفق')),
                ('ease_factor', models.FloatField(default=2.5, verbose_name='ضریب سهولت SuperMemo')),
                ('is_mastered', models.BooleanField(default=False, verbose_name='تسلط کامل یافته')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_spaced_reviews', to=settings.AUTH_USER_MODEL, verbose_name='زبان\u200cآموز هدف (یا همه)')),
                ('teacher_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaced_review_items', to='teachers.teacherclass', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'آیتم مرور با فاصله (SRS)',
                'verbose_name_plural': 'آیتم\u200cهای مرور با فاصله',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_type', models.CharField(choices=[('lesson', 'طرح درس'), ('activity', 'فعالیت کلاسی'), ('worksheet', 'کاربرگ تمرین'), ('assessment', 'آزمون و کوئیز')], db_index=True, max_length=32, verbose_name='نوع محتوا')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان محتوا')),
                ('topic', models.CharField(blank=True, default='', max_length=255, verbose_name='موضوع درس')),
                ('cefr_level', models.CharField(default='B1', max_length=16, verbose_name='سطح CEFR')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='محتوای ساختاریافته')),
                ('raw_markdown', models.TextField(blank=True, default='', verbose_name='متن کامل یا مارک\u200cداون')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('approved', 'تایید شده'), ('archived', 'بایگانی شده')], db_index=True, default='draft', max_length=32, verbose_name='وضعیت محتوا')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='سنجاق به علاقه\u200cمندی\u200cها')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متاداده آموزشی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_materials', to=settings.AUTH_USER_MODEL, verbose_name='مدرس سازنده')),
                ('teacher_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='teachers.teacherclass', verbose_name='کلاس مرتبط')),
            ],
            options={
                'verbose_name': 'محتوای آموزشی TeacherOS',
                'verbose_name_plural': 'محتواهای آموزشی TeacherOS',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DifferentiationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier_support', models.JSONField(default=dict, verbose_name='سطح پشتیبانی (برای یادگیرندگان نیازمند کمک)')),
                ('tier_core', models.JSONField(default=dict, verbose_name='سطح استاندارد')),
                ('tier_extension', models.JSONField(default=dict, verbose_name='سطح چالشی (برای یادگیرندگان پیشرفته)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differentiation_plans', to='teachers.teacherclass', verbose_name='کلاس')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differentiation_plans', to='teachers.teachermaterial', verbose_name='محتوای مبنا')),
            ],
            options={
                'verbose_name': 'برنامه تمایزیافته آموزشی',
                'verbose_name_plural': 'برنامه\u200cهای تمایزیافته آموزشی',
            },
        ),
        migrations.CreateModel(
            name='StudentDossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_goals', models.JSONField(blank=True, default=dict, verbose_name='اهداف کوتاه\u200cمدت و بلندمدت')),
                ('learning_preferences', models.JSONField(blank=True, default=dict, verbose_name='ترجیحات یادگیری و رفتار')),
                ('cefr_skills', models.JSONField(blank=True, default=dict, verbose_name='سطوح و اعتمادبه\u200cنفس ۷ مهارت')),
                ('skill_scores_history', models.JSONField(blank=True, default=list, verbose_name='سوابق ارزیابی هفت مهارت (از ۲۰)')),
                ('error_profile', models.JSONField(blank=True, default=list, verbose_name='پروفایل خطاهای زبانی')),
                ('strengths', models.JSONField(blank=True, default=list, verbose_name='نقاط قوت')),
                ('areas_for_development', models.JSONField(blank=True, default=list, verbose_name='نقاط نیازمند تقویت')),
                ('engagement_index', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, verbose_name='شاخص تعامل و نظم کلاسی')),
                ('ai_recommendations', models.JSONField(blank=True, default=list, verbose_name='پیشنهادات هوشمند AI')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to=settings.AUTH_USER_MODEL, verbose_name='زبان\u200cآموز')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentored_dossiers', to=settings.AUTH_USER_MODEL, verbose_name='مدرس مسئول')),
                ('teacher_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_dossiers', to='teachers.teacherclass', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'پرونده آموزشی دانش\u200cآموز (Dossier)',
                'verbose_name_plural': 'پرونده\u200cهای آموزشی دانش\u200cآموزان',
                'unique_together': {('teacher_class', 'learner')},
            },
        ),
    ]
