# Generated by Django 5.2.17 on 2026-09-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_lessonoutcome_spacedreviewitem_teachermaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdossier',
            name='assessment_milestones',
            field=models.JSONField(blank=True, default=list, verbose_name='نقاط عطف و نتایج آزمون\u200cها'),
        ),
        migrations.AddField(
            model_name='teachermaterial',
            name='subtype',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='زیرنوع محتوا'),
        ),
    ]
