# Generated by Django 5.2.17 on 2026-09-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_studentdossier_assessment_milestones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclass',
            name='age_group',
            field=models.CharField(blank=True, default='adult', max_length=32, verbose_name='گروه سنی'),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='class_size_type',
            field=models.CharField(blank=True, default='small', max_length=32, verbose_name='نوع و اندازه کلاس'),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='coursebook',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='کتاب و منابع آموزشی'),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='default_duration',
            field=models.PositiveIntegerField(default=60, verbose_name='مدت زمان پیش\u200cفرض جلسه (دقیقه)'),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='equipment',
            field=models.JSONField(blank=True, default=list, verbose_name='امکانات و تجهیزات کلاسی'),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='focus_skills',
            field=models.JSONField(blank=True, default=list, verbose_name='مهارت\u200cهای نیازمند تمرکز'),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='goal',
            field=models.CharField(blank=True, default='general', max_length=64, verbose_name='هدف اصلی دوره'),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='target_exams',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='آزمون\u200cهای هدف'),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='teaching_preferences',
            field=models.JSONField(blank=True, default=list, verbose_name='رویکردها و ترجیحات تدریس'),
        ),
    ]
