# Generated by Django 5.2.17 on 2026-09-16 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_teacherclass_age_group_teacherclass_class_size_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPedagogicalPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_code', models.CharField(default='pro', max_length=32, verbose_name='کد طرح اشتراک')),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای طرح')),
                ('default_cefr', models.CharField(default='B1', max_length=16, verbose_name='سطح زبانی پیش\u200cفرض')),
                ('default_duration', models.PositiveIntegerField(default=60, verbose_name='مدت جلسه پیش\u200cفرض')),
                ('preferred_methodology', models.CharField(default='ppp', max_length=32, verbose_name='متدولوژی تدریس ترجیحی')),
                ('auto_generate_ccqs', models.BooleanField(default=True, verbose_name='تولید خودکار سوالات مفهومی CCQ')),
                ('feedback_tone', models.CharField(default='balanced', max_length=32, verbose_name='لحن بازخورد رایتینگ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedagogical_preferences', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'تنظیمات آموزشی و ترجیحات مدرس',
                'verbose_name_plural': 'تنظیمات آموزشی و ترجیحات مدرسان',
            },
        ),
    ]
