# Generated by Django 5.2.17 on 2026-09-14 19:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IELTSPassageTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='ترتیب در بخش (مثلاً Passage 1/2/3 یا Writing Task 1/2 یا Speaking Part 1/2/3)')),
                ('title', models.CharField(max_length=255)),
                ('content_text', models.TextField(blank=True, default='', help_text='متن متن ریدینگ، موضوع انشا، سوالات لیسنینگ یا کارت اسپیکینگ')),
                ('media_image_url', models.URLField(blank=True, default='', help_text='نمودار تسک ۱ رایتینگ یا تصویر نقشه/دیاگرام')),
                ('word_count', models.PositiveIntegerField(default=0, help_text='تعداد کلمات متن یا حداقل کلمات مورد انتظار')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='تنظیمات ویژه (مثل prep_time_seconds, speaking_time_seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IELTS Passage / Task',
                'verbose_name_plural': 'IELTS Passages / Tasks',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='IELTSSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('listening', 'Listening / شنیداری'), ('reading', 'Reading / خواندن و درک مطلب'), ('writing', 'Writing / نگارش'), ('speaking', 'Speaking / گفتار و مکالمه')], db_index=True, max_length=24)),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='ترتیب اجرای بخش (1=Listening, 2=Reading, 3=Writing, 4=Speaking)')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='مدت زمان اختصاصی این بخش به دقیقه')),
                ('instructions_en', models.TextField(blank=True, default='')),
                ('instructions_fa', models.TextField(blank=True, default='')),
                ('audio_media_url', models.URLField(blank=True, default='', help_text='آدرس فایل صوتی برای Listening یا Speaking')),
                ('audio_script', models.TextField(blank=True, default='', help_text='متن کامل صوت (اسکریپت) برای بازبینی و تصحیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IELTS Section',
                'verbose_name_plural': 'IELTS Sections',
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='IELTSBandDescriptor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criteria_key', models.CharField(choices=[('task_achievement_response', 'Task Achievement / Response (TA/TR)'), ('coherence_cohesion', 'Coherence & Cohesion (CC)'), ('lexical_resource', 'Lexical Resource (LR)'), ('grammatical_range_accuracy', 'Grammatical Range & Accuracy (GRA)'), ('fluency_coherence', 'Fluency & Coherence (FC - Speaking)'), ('pronunciation', 'Pronunciation (PR - Speaking)')], db_index=True, max_length=40)),
                ('band_level', models.DecimalField(decimal_places=1, help_text='نمره باند (۱.۰ تا ۹.۰)', max_digits=2)),
                ('section_type', models.CharField(choices=[('writing', 'Writing'), ('speaking', 'Speaking')], db_index=True, max_length=24)),
                ('public_descriptor_en', models.TextField(help_text='متن رسمی و عمومی توصیف\u200cگر باند در آزمون آیلتس')),
                ('pedagogical_guidance_fa', models.TextField(help_text='راهنما و شاخص\u200cهای آموزشی فارسی برای مصححان و داوطلبان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IELTS Band Descriptor',
                'verbose_name_plural': 'IELTS Band Descriptors',
                'ordering': ['section_type', 'criteria_key', '-band_level'],
                'unique_together': {('section_type', 'criteria_key', 'band_level')},
            },
        ),
        migrations.CreateModel(
            name='IELTSQuestionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('multiple_choice_single', 'Multiple Choice (Single) / چندگزینه\u200cای تک\u200cجواب'), ('multiple_choice_multiple', 'Multiple Choice (Multi) / چندگزینه\u200cای چندجواب'), ('true_false_not_given', 'True / False / Not Given (T/F/NG)'), ('yes_no_not_given', 'Yes / No / Not Given (Y/N/NG)'), ('matching_headings', 'Matching Headings / تطبیق عناوین'), ('matching_information', 'Matching Information / تطبیق اطلاعات'), ('matching_features', 'Matching Features / تطبیق ویژگی\u200cها'), ('sentence_completion', 'Sentence Completion / تکمیل جملات'), ('summary_completion', 'Summary Completion / تکمیل خلاصه'), ('note_form_completion', 'Note / Form Completion / تکمیل یادداشت یا فرم'), ('diagram_map_labelling', 'Diagram / Map Labelling / برچسب\u200cگذاری نقشه یا نمودار'), ('table_flowchart_completion', 'Table / Flowchart Completion / تکمیل جدول یا فلوچارت'), ('writing_task1_academic', 'Academic Writing Task 1 / گزارش نمودار یا فرآیند'), ('writing_task1_general', 'General Writing Task 1 / نگارش نامه'), ('writing_task2_essay', 'Writing Task 2 / نگارش مقاله تحلیلی'), ('speaking_part1', 'Speaking Part 1 / مصاحبه و احوال\u200cپرسی'), ('speaking_part2_cue_card', 'Speaking Part 2 / صحبت ۲ دقیقه\u200cای با کیوکارت'), ('speaking_part3_discussion', 'Speaking Part 3 / بحث و تحلیل انتزاعی')], db_index=True, max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('instructions', models.TextField(help_text='دستورالعمل سوال (مثلاً: Choose NO MORE THAN TWO WORDS from the passage)')),
                ('heading_options', models.JSONField(blank=True, default=list, help_text="بانک عناوین یا گزینه\u200cهای تطبیقی (مثلاً: ['i', 'ii', 'iii', ...])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passage_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='ielts.ieltspassagetask')),
            ],
            options={
                'verbose_name': 'IELTS Question Group',
                'verbose_name_plural': 'IELTS Question Groups',
                'ordering': ['passage_task', 'order'],
            },
        ),
        migrations.CreateModel(
            name='IELTSQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.PositiveIntegerField(help_text='شماره سراسری سوال در بخش (مثلاً ۱ تا ۴۰ در لیسنینگ یا ریدینگ)')),
                ('prompt_text', models.TextField(help_text='صورت سوال یا عبارت دارای جای خالی (...)')),
                ('options', models.JSONField(blank=True, default=list, help_text="گزینه\u200cهای چهارجوابی (مثلاً [{'id': 'A', 'text': '...'}, ...])")),
                ('correct_answers', models.JSONField(default=list, help_text='پاسخ\u200cهای صحیح قابل قبول (شامل انواع املاها و حروف بزرگ/کوچک)')),
                ('explanation', models.TextField(blank=True, default='', help_text='تحلیل تشریحی و آدرس پاسخ در متن آزمون')),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ielts.ieltsquestiongroup')),
            ],
            options={
                'verbose_name': 'IELTS Question',
                'verbose_name_plural': 'IELTS Questions',
                'ordering': ['group', 'question_number'],
            },
        ),
        migrations.AddField(
            model_name='ieltspassagetask',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages_tasks', to='ielts.ieltssection'),
        ),
        migrations.CreateModel(
            name='IELTSTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_en', models.CharField(help_text='English title of the test', max_length=255)),
                ('title_fa', models.CharField(help_text='عنوان فارسی آزمون', max_length=255)),
                ('test_type', models.CharField(choices=[('academic', 'Academic / آکادمیک'), ('general_training', 'General Training / جنرال ترینینگ')], db_index=True, default='academic', max_length=32)),
                ('version', models.PositiveIntegerField(default=1, help_text='شماره نسخه آزمون (افزایشی در صورت بازبینی)')),
                ('status', models.CharField(choices=[('draft', 'Draft / پیش\u200cنویس'), ('in_review', 'In Review / در حال بازبینی'), ('approved', 'Approved / تأیید شده'), ('published', 'Published / منتشر شده'), ('archived', 'Archived / بایگانی شده')], db_index=True, default='draft', max_length=24)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='', help_text='یادداشت\u200cها و توضیحات تأیید کیفی بازبین')),
                ('is_locked', models.BooleanField(default=False, help_text='قفل شدن ویرایش محتوا پس از انتشار یا ثبت نخستین تلاش زبان\u200cآموز')),
                ('quality_checklist', models.JSONField(blank=True, default=dict, help_text='چک\u200cلیست تأیید کیفی شامل اصالت، کالیبراسیون CEFR و تایپوگرافی')),
                ('copyright_source', models.CharField(help_text='تأییدیه و شناسه مالکیت معنوی محتوا (تولید اختصاصی و عدم نقض کپی\u200cرایت کمبریج/بریتیش کانسیل)', max_length=500)),
                ('disclaimer_label', models.CharField(default='IELTS-like practice — not official IELTS / تمرین شبیه\u200cساز آیلتس — غیررسمی', help_text='سلب مسئولیت رسمی و هشدار آزمون غیررسمی', max_length=255)),
                ('total_duration_minutes', models.PositiveIntegerField(default=165, help_text='مدت زمان کل آزمون به دقیقه')),
                ('difficulty_level', models.CharField(default='Band 6.0 - 7.5', help_text='سطح هدف آزمون (مثلاً Band 5.5-6.5 یا 7.0-8.5)', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, help_text='طراح یا مؤلف اصلی محتوای آزمون', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_ielts_tests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='بازبین مستقل آزمون (باید با نویسنده متفاوت باشد)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ielts_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IELTS Test',
                'verbose_name_plural': 'IELTS Tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ieltssection',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ielts.ieltstest'),
        ),
        migrations.AlterUniqueTogether(
            name='ieltssection',
            unique_together={('test', 'section_type')},
        ),
    ]
