# Generated by Django 5.2.17 on 2026-09-14 19:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IELTSTestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('full_simulation', 'Full Exam Simulation / شبیه\u200cساز کامل آزمون'), ('listening_practice', 'Listening Practice / تمرین شنیداری'), ('reading_practice', 'Reading Practice / تمرین درک مطلب'), ('writing_practice', 'Writing Practice / تمرین نگارش'), ('speaking_practice', 'Speaking Practice / تمرین مکالمه')], db_index=True, default='full_simulation', max_length=32)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress / در حال برگزاری'), ('submitted', 'Submitted / پایان\u200cیافته و ثبت\u200cشده'), ('timed_out', 'Timed Out / اتمام زمان قانونی'), ('abandoned', 'Abandoned / رها شده')], db_index=True, default='in_progress', max_length=24)),
                ('current_section_index', models.PositiveSmallIntegerField(default=0, help_text='شاخص بخش فعلی در آزمون (0=Listening, 1=Reading, ...)')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(help_text='زمان انقضای قطعی بخش/آزمون بر اساس ساعت سرور')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('responses', models.JSONField(blank=True, default=dict, help_text='پاسخ\u200cهای زبان\u200cآموز به تفکیک شناسه سوال: { question_id: answer_val }')),
                ('flagged_questions', models.JSONField(blank=True, default=list, help_text='فهرست شناسه\u200cهای سوالات نشانه\u200cگذاری\u200cشده برای بازبینی: [ question_id, ... ]')),
                ('section_timings', models.JSONField(blank=True, default=dict, help_text='تاریخچه زمان\u200cبندی بخش\u200cها و مدت زمان سپری\u200cشده')),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, help_text='مجموع نمرات خام کسب\u200cشده (مثلاً ۳۵ از ۴۰)', max_digits=5, null=True)),
                ('scaled_band_score', models.DecimalField(blank=True, decimal_places=1, help_text='نمره باند استاندارد آیلتس (۱.۰ تا ۹.۰ با گام\u200cهای ۰.۵)', max_digits=3, null=True)),
                ('section_scores', models.JSONField(blank=True, default=dict, help_text='نمرات تفکیکی مهارت\u200cها: { listening: { raw, band, total }, reading: ... }')),
                ('diagnostics', models.JSONField(blank=True, default=dict, help_text='تحلیل تشخیصی عملکرد به تفکیک فرمت سوال و سطح CEFR')),
                ('disclaimer_acknowledged', models.BooleanField(default=True, help_text='تأیید غیررسمی بودن شبیه\u200cساز آیلتس توسط زبان\u200cآموز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(help_text='زبان\u200cآموز شرکت\u200cکننده در آزمون', on_delete=django.db.models.deletion.CASCADE, related_name='ielts_sessions', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(help_text='نسخه آزمون آیلتس انتخاب\u200cشده', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ielts.ieltstest')),
            ],
            options={
                'verbose_name': 'IELTS Test Session',
                'verbose_name_plural': 'IELTS Test Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
