# Generated by Django 5.2.17 on 2026-09-14 20:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0002_ieltstestsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IELTSWritingSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft / پیش\u200cنویس ذخیره\u200cشده'), ('submitted', 'Submitted / ارسال\u200cشده برای تصحیح'), ('evaluated', 'Evaluated / ارزیابی\u200cشده')], db_index=True, default='draft', max_length=24)),
                ('task1_prompt_title', models.CharField(blank=True, default='', max_length=255)),
                ('task1_prompt_text', models.TextField(blank=True, default='')),
                ('task1_image_url', models.URLField(blank=True, default='')),
                ('task1_text', models.TextField(blank=True, default='')),
                ('task1_word_count', models.PositiveIntegerField(default=0)),
                ('task1_time_seconds', models.PositiveIntegerField(default=0)),
                ('task1_scores', models.JSONField(blank=True, default=dict, help_text='نمرات تفکیکی معیارهای تسک ۱: { ta: 6.5, cc: 6.0, lr: 7.0, gra: 6.5, band: 6.5 }')),
                ('task2_prompt_title', models.CharField(blank=True, default='', max_length=255)),
                ('task2_prompt_text', models.TextField(blank=True, default='')),
                ('task2_text', models.TextField(blank=True, default='')),
                ('task2_word_count', models.PositiveIntegerField(default=0)),
                ('task2_time_seconds', models.PositiveIntegerField(default=0)),
                ('task2_scores', models.JSONField(blank=True, default=dict, help_text='نمرات تفکیکی معیارهای تسک ۲: { tr: 6.5, cc: 6.5, lr: 7.0, gra: 6.0, band: 6.5 }')),
                ('overall_band', models.DecimalField(blank=True, decimal_places=1, help_text='نمره باند کل بر اساس فرمول وزنی استاندارد آیلتس (یک\u200cسوم تسک ۱ + دوسوم تسک ۲)', max_digits=3, null=True)),
                ('overall_band_min', models.DecimalField(blank=True, decimal_places=1, help_text='حداقل دامنه تخمینی باند (عدم قطعیت هوش مصنوعی)', max_digits=3, null=True)),
                ('overall_band_max', models.DecimalField(blank=True, decimal_places=1, help_text='حداکثر دامنه تخمینی باند', max_digits=3, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.85'), help_text='میزان اطمینان مدل تشخیصی به نمره تخمین\u200cزده\u200cشده (۰ تا ۱)', max_digits=4)),
                ('cefr_level', models.CharField(default='B2', help_text='سطح معادل CEFR (مثلاً B2 یا C1)', max_length=8)),
                ('criteria_breakdown', models.JSONField(blank=True, default=dict, help_text='توصیف\u200cگرهای معیارها و فیدبک تشخیصی چهارگانه')),
                ('annotations', models.JSONField(blank=True, default=list, help_text='پیشنهادهای اصلاحی درون\u200cمتنی، گرامر، واژگان و ساختار جملات')),
                ('pedagogical_advice', models.JSONField(blank=True, default=list, help_text='توصیه\u200cهای کاربردی به فارسی برای بهبود نگارش و افزایش نمره باند')),
                ('teacher_review_requested', models.BooleanField(default=False, help_text='درخواست تصحیح و نمره\u200cدهی توسط اگزمینر/مدرس رسمی ایندورا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(help_text='زبان\u200cآموز نویسنده متن', on_delete=django.db.models.deletion.CASCADE, related_name='ielts_writing_submissions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, help_text='جلسه آزمون مرتبط در صورت آزمون جامع', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writing_submissions', to='ielts.ieltstestsession')),
                ('test', models.ForeignKey(blank=True, help_text='آزمون مرتبط (اختیاری در صورت تمرین مستقل)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writing_submissions', to='ielts.ieltstest')),
            ],
            options={
                'verbose_name': 'IELTS Writing Submission',
                'verbose_name_plural': 'IELTS Writing Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
