# Generated by Django 5.2.17 on 2026-09-14 21:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0003_ieltswritingsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IELTSSpeakingSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft / پیش\u200cنویس'), ('submitted', 'Submitted / ارسال\u200cشده'), ('evaluated', 'Evaluated / ارزیابی\u200cشده')], db_index=True, default='draft', max_length=24)),
                ('part1_prompt_title', models.CharField(blank=True, default='', max_length=255)),
                ('part1_questions', models.JSONField(blank=True, default=list, help_text='فهرست سوالات پارت ۱')),
                ('part1_recording_url', models.URLField(blank=True, default='')),
                ('part1_transcript', models.TextField(blank=True, default='')),
                ('part1_duration_seconds', models.PositiveIntegerField(default=0)),
                ('part2_cue_card_title', models.CharField(blank=True, default='', max_length=255)),
                ('part2_cue_card_prompt', models.TextField(blank=True, default='')),
                ('part2_bullet_points', models.JSONField(blank=True, default=list)),
                ('part2_prep_notes', models.TextField(blank=True, default='', help_text='یادداشت\u200cهای ۱ دقیقه\u200cای داوطلب')),
                ('part2_prep_time_seconds', models.PositiveIntegerField(default=60)),
                ('part2_recording_url', models.URLField(blank=True, default='')),
                ('part2_transcript', models.TextField(blank=True, default='')),
                ('part2_duration_seconds', models.PositiveIntegerField(default=0)),
                ('part3_prompt_title', models.CharField(blank=True, default='', max_length=255)),
                ('part3_questions', models.JSONField(blank=True, default=list, help_text='فهرست سوالات تحلیلی پارت ۳')),
                ('part3_recording_url', models.URLField(blank=True, default='')),
                ('part3_transcript', models.TextField(blank=True, default='')),
                ('part3_duration_seconds', models.PositiveIntegerField(default=0)),
                ('fc_score', models.DecimalField(blank=True, decimal_places=1, help_text='Fluency and Coherence (FC) نمره روانی و انسجام کلامی', max_digits=3, null=True)),
                ('lr_score', models.DecimalField(blank=True, decimal_places=1, help_text='Lexical Resource (LR) نمره دامنه واژگان و اصطلاحات', max_digits=3, null=True)),
                ('gra_score', models.DecimalField(blank=True, decimal_places=1, help_text='Grammatical Range and Accuracy (GRA) نمره تنوع و دقت گرامری', max_digits=3, null=True)),
                ('pr_score', models.DecimalField(blank=True, decimal_places=1, help_text='Pronunciation (PR) نمره تلفظ، ریتم و وضوح کلامی', max_digits=3, null=True)),
                ('overall_band', models.DecimalField(blank=True, decimal_places=1, help_text='میانگین ۴ معیار با گرد کردن نیم\u200cباندی رسمی آیلتس', max_digits=3, null=True)),
                ('overall_band_min', models.DecimalField(blank=True, decimal_places=1, help_text='حداقل بازه اطمینان تخمین باند', max_digits=3, null=True)),
                ('overall_band_max', models.DecimalField(blank=True, decimal_places=1, help_text='حداکثر بازه اطمینان تخمین باند', max_digits=3, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.85'), help_text='درجه اطمینان مدل تشخیصی به نمره تخمین\u200cزده\u200cشده (۰ تا ۱)', max_digits=4)),
                ('cefr_level', models.CharField(default='B2', help_text='سطح معادل CEFR (مثلاً B2 یا C1)', max_length=8)),
                ('criteria_breakdown', models.JSONField(blank=True, default=dict, help_text='توصیف\u200cگرهای تفکیکی ۴ معیار رسمی')),
                ('fluency_metrics', models.JSONField(blank=True, default=dict, help_text='شاخص\u200cهای روانی کلام: سرعت سخن\u200cگویی (WPM)، مکث\u200cها، تکرارها و مارکرهای پیوستگی')),
                ('pronunciation_diagnostics', models.JSONField(blank=True, default=dict, help_text='تحلیل وضوح گفتاری و تشخیص چالش\u200cهای آوایی بومی زبان فارسی (قانون ۸ مرامنامه)')),
                ('annotations', models.JSONField(blank=True, default=list, help_text='یادداشت\u200cها و پیشنهادهای درون\u200cمتنی روی متن پیاده\u200cشده')),
                ('pedagogical_advice', models.JSONField(blank=True, default=list, help_text='توصیه\u200cهای آموزشی به فارسی برای ارتقای نمره اسپیکینگ')),
                ('teacher_review_requested', models.BooleanField(default=False, help_text='درخواست ارزیابی رسمی توسط اگزمینر انسان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(help_text='زبان\u200cآموز متقاضی آزمون مکالمه', on_delete=django.db.models.deletion.CASCADE, related_name='ielts_speaking_submissions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, help_text='جلسه آزمون مرتبط در صورت ماک جامع', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaking_submissions', to='ielts.ieltstestsession')),
                ('test', models.ForeignKey(blank=True, help_text='آزمون مرتبط (اختیاری در صورت تمرین مستقل)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaking_submissions', to='ielts.ieltstest')),
            ],
            options={
                'verbose_name': 'IELTS Speaking Submission',
                'verbose_name_plural': 'IELTS Speaking Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
