# Generated by Django 5.2.17 on 2026-08-19 07:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal', models.CharField(blank=True, choices=[('general_english', 'General English'), ('conversation', 'Conversation'), ('ielts', 'IELTS'), ('academic', 'Academic English'), ('work', 'Work and career'), ('travel', 'Travel'), ('school', 'School English'), ('other', 'Other')], max_length=32)),
                ('age_band', models.CharField(blank=True, choices=[('under_13', 'Under 13'), ('13_15', '13-15'), ('16_17', '16-17'), ('18_24', '18-24'), ('25_34', '25-34'), ('35_44', '35-44'), ('45_plus', '45+'), ('prefer_not', 'Prefer not to say')], max_length=16)),
                ('current_estimate', models.CharField(choices=[('unknown', "I don't know"), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='unknown', max_length=16)),
                ('preferred_daily_minutes', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(240)])),
                ('preferred_days', models.JSONField(blank=True, default=list)),
                ('timezone', models.CharField(default='Asia/Tehran', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('learner', 'Learner'), ('teacher', 'Teacher')], max_length=16)),
                ('stage', models.CharField(choices=[('role', 'Role'), ('basic_profile', 'Basic profile'), ('preferences', 'Preferences'), ('consent', 'Consent'), ('review', 'Review'), ('completed', 'Completed')], default='role', max_length=32)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('completed_steps', models.JSONField(blank=True, default=list)),
                ('draft_data', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_name', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True, max_length=1500)),
                ('experience_years', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('availability_intent', models.BooleanField(default=False)),
                ('verification_intent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('public_name', 'user_id'),
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at',),
                'indexes': [models.Index(fields=['user', 'status', 'requested_at'], name='profiles_export_lookup_idx')],
            },
        ),
    ]
