# Generated by Django 5.2.17 on 2026-09-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='گواهینامه\u200cهای بین\u200cالمللی مانند CELTA, IELTS و...'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='education',
            field=models.JSONField(blank=True, default=list, help_text='سوابق تحصیلی و مدارک دانشگاهی'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='headline',
            field=models.CharField(blank=True, default='', help_text='عنوان حرفه\u200cای و مختصر مدرس', max_length=200),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='hourly_rate_toman',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='نرخ پایه جلسات به تومان', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='response_time_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='میانگین زمان پاسخگویی به دقیقه'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='video_intro_url',
            field=models.URLField(blank=True, default='', help_text='لینک ویدیوی معرفی مدرس', max_length=500),
        ),
    ]
