# Generated by Django 5.2.17 on 2026-09-06 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='شناسه یکتا')),
                ('icon', models.CharField(blank=True, default='help-circle', max_length=64, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی سوالات متداول',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای سوالات متداول',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255, verbose_name='سوال')),
                ('normalized_question', models.CharField(blank=True, db_index=True, max_length=255)),
                ('answer', models.TextField(verbose_name='پاسخ تایید شده')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='منتشر شده')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد مشاهده')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='تعداد رای مفید')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='برچسب\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='support.faqcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['order', '-helpful_count', 'question'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('payments', 'پرداخت و امور مالی'), ('account', 'حساب کاربری'), ('security', 'امنیت و دسترسی'), ('courses', 'دوره\u200cها و محتوای آموزشی'), ('technical', 'مشکلات فنی پلتفرم'), ('community', 'جامعه و گزارش\u200cها'), ('other', 'سایر موارد')], db_index=True, max_length=32, verbose_name='دسته\u200cبندی موضوع')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان درخواست')),
                ('description', models.TextField(verbose_name='توضیحات و شرح مشکل')),
                ('status', models.CharField(choices=[('new', 'در انتظار بررسی'), ('triaged', 'دسته\u200cبندی شده'), ('ai_answered', 'پاسخ هوشمند با استناد'), ('escalated', 'ارجاع به پشتیبان انسانی'), ('resolved', 'حل شده'), ('closed', 'بسته شده')], db_index=True, default='new', max_length=32, verbose_name='وضعیت تیکت')),
                ('escalated_to_human', models.BooleanField(db_index=True, default=False, verbose_name='ارجاع به انسان')),
                ('escalation_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='علت ارجاع')),
                ('ai_confidence_score', models.FloatField(blank=True, null=True, verbose_name='ضریب اطمینان پاسخ هوشمند')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cited_faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cited_tickets', to='support.faqitem', verbose_name='سوال متداول استناد شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت پشتیبانی',
                'verbose_name_plural': 'تیکت\u200cهای پشتیبانی',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('file_url', models.CharField(max_length=512, verbose_name='آدرس فایل')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم فایل (بایت)')),
                ('content_type', models.CharField(blank=True, default='application/octet-stream', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.supportticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پیوست تیکت',
                'verbose_name_plural': 'پیوست\u200cهای تیکت',
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'کاربر'), ('ai_agent', 'دستیار هوشمند'), ('staff', 'کارشناس پشتیبانی')], default='user', max_length=16, verbose_name='فرستنده')),
                ('body', models.TextField(verbose_name='متن پیام')),
                ('is_internal', models.BooleanField(default=False, verbose_name='یادداشت داخلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر فرستنده')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پیام تیکت',
                'verbose_name_plural': 'پیام\u200cهای تیکت',
                'ordering': ['created_at'],
            },
        ),
    ]
