# Generated by Django 5.2.17 on 2026-09-20 16:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumBookMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('track', models.CharField(choices=[('adult_general', 'دوره\u200cهای عمومی بزرگسالان'), ('young_learners', 'کودک و نوجوان'), ('exam_prep_ielts', 'آمادگی آزمون آیلتس (IELTS)'), ('exam_prep_toefl', 'آمادگی آزمون تافل (TOEFL)'), ('exam_prep_advanced', 'آزمون\u200cهای پیشرفته کمبریج (CAE)')], db_index=True, default='adult_general', max_length=32)),
                ('min_cefr', models.CharField(db_index=True, default='A1', max_length=8)),
                ('max_cefr', models.CharField(default='A1', max_length=8)),
                ('min_age', models.PositiveIntegerField(default=13)),
                ('max_age', models.PositiveIntegerField(default=99)),
                ('book_title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=128)),
                ('edition', models.CharField(blank=True, default='', max_length=64)),
                ('description_fa', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('syllabus_json', models.JSONField(blank=True, default=dict, help_text='Detailed syllabus containing units, target grammar points, vocabulary volume, speaking goals.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نگاشت کتاب آموزشی',
                'verbose_name_plural': 'نگاشت\u200cهای کتب آموزشی',
                'ordering': ['track', 'min_cefr', 'book_title'],
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_format', models.CharField(choices=[('solo', 'انفرادی (۱ به ۱)'), ('group', 'گروهی (تا ۴ نفر)')], default='group', max_length=16, verbose_name='قالب کلاس درخواستی')),
                ('max_classmates', models.PositiveIntegerField(default=3, help_text='حداکثر تعداد همکلاسی\u200cها (۱ تا ۳ نفر؛ مجموعاً ۲ تا ۴ نفر در کلاس)')),
                ('available_slots_json', models.JSONField(blank=True, default=list, help_text='لیست روزها و ساعت\u200cهای در دسترس کاربر (مثلا: شنبه صبح، دوشنبه عصر)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پذیرش مدرس'), ('claimed', 'پذیرفته شده توسط مدرس'), ('matched', 'تشکیل شده در کلاس'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=24, verbose_name='وضعیت درخواست')),
                ('student_notes', models.TextField(blank=True, default='', verbose_name='یادداشت زبان\u200cآموز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_class_requests', to=settings.AUTH_USER_MODEL, verbose_name='مدرس پذیرنده')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollment_requests', to=settings.AUTH_USER_MODEL, verbose_name='زبان\u200cآموز')),
                ('target_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_requests', to='live_classes.curriculumbookmapping', verbose_name='کتاب هدف پیشنهادی')),
            ],
            options={
                'verbose_name': 'درخواست ثبت\u200cنام کلاس آنلاین',
                'verbose_name_plural': 'درخواست\u200cهای ثبت\u200cنام کلاس آنلاین',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveClassCohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان کلاس')),
                ('class_format', models.CharField(choices=[('solo', 'انفرادی (۱ به ۱)'), ('group', 'گروهی (تا ۴ نفر)')], default='group', max_length=16, verbose_name='نوع کلاس')),
                ('max_capacity', models.PositiveIntegerField(default=4, verbose_name='حداکثر ظرفیت (۱ تا ۴ نفر)')),
                ('meeting_url', models.URLField(blank=True, default='', max_length=500, verbose_name='لینک کلاس آنلاین (اسکای\u200cروم / گوگل میت)')),
                ('schedule_summary', models.CharField(blank=True, default='', max_length=255, verbose_name='برنامه برگزاری جلسات')),
                ('next_session_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان جلسه بعدی')),
                ('status', models.CharField(choices=[('active', 'فعال و در حال برگزاری'), ('completed', 'به پایان رسیده'), ('paused', 'متوقف شده')], db_index=True, default='active', max_length=24, verbose_name='وضعیت دوره')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_cohorts', to='live_classes.curriculumbookmapping', verbose_name='کتاب و سرفصل آموزشی')),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_cohorts', to=settings.AUTH_USER_MODEL, verbose_name='زبان\u200cآموزان کلاس')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_cohorts', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'گروه کلاسی آنلاین',
                'verbose_name_plural': 'گروه\u200cهای کلاسی آنلاین',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSessionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_number', models.PositiveIntegerField(default=1, verbose_name='شماره جلسه')),
                ('units_covered', models.CharField(max_length=255, verbose_name='درس\u200cها و بخش\u200cهای تدریس شده')),
                ('grammar_covered', models.TextField(blank=True, default='', verbose_name='نکات گرامری آموزش داده شده')),
                ('vocabulary_list', models.JSONField(blank=True, default=list, verbose_name='واژگان کلیدی جلسه')),
                ('homework_description', models.TextField(blank=True, default='', verbose_name='تکالیف منزل')),
                ('teacher_notes', models.TextField(blank=True, default='', verbose_name='یادداشت عملکرد و پیشرفت')),
                ('session_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ جلسه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='live_classes.liveclasscohort', verbose_name='کلاس')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_sessions', to=settings.AUTH_USER_MODEL, verbose_name='مدرس ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'گزارش جلسه تدریس',
                'verbose_name_plural': 'گزارش\u200cهای جلسات تدریس',
                'ordering': ['-session_date', '-session_number'],
            },
        ),
    ]
