# Generated by Django 5.2.17 on 2026-09-15 20:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disaster_recovery', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunbookDefinition',
            fields=[
                ('slug', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_fa', models.CharField(max_length=255)),
                ('severity_trigger', models.CharField(max_length=16)),
                ('target_service', models.CharField(max_length=64)),
                ('steps_json', models.JSONField(blank=True, default=list)),
                ('automated_verification_available', models.BooleanField(default=True)),
                ('last_rehearsed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('P1_CRITICAL', 'P1 - بحرانی (قطعی سرویس / خطر داده)'), ('P2_HIGH', 'P2 - بالا (اختلال در درگاه پرداخت یا هوش مصنوعی)'), ('P3_MEDIUM', 'P3 - متوسط (کندی سیستم یا خطای غیراصلی)'), ('P4_LOW', 'P4 - جزئی (مشکل ظاهری یا گزارش کوچک)')], db_index=True, default='P3_MEDIUM', max_length=16)),
                ('status', models.CharField(choices=[('detected', 'شناسایی\u200cشده'), ('investigating', 'در حال بررسی'), ('mitigated', 'مهارشده / کاهش اثر'), ('resolved', 'رفع قطعی'), ('post_mortem', 'تحلیل پس از بحران')], db_index=True, default='detected', max_length=16)),
                ('affected_service', models.CharField(db_index=True, max_length=64)),
                ('runbook_slug', models.CharField(blank=True, default='', max_length=64)),
                ('summary', models.TextField()),
                ('mitigation_steps', models.TextField(blank=True, default='')),
                ('root_cause_analysis', models.TextField(blank=True, default='')),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mitigated_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-detected_at',),
            },
        ),
        migrations.CreateModel(
            name='RestoreVerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_file_path', models.CharField(max_length=255)),
                ('checksum', models.CharField(max_length=64)),
                ('checksum_verified', models.BooleanField(default=True)),
                ('tables_restored_count', models.PositiveIntegerField(default=0)),
                ('records_sampled_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('verified', 'کاملاً تأییدشده'), ('partial', 'تأیید نسبی'), ('failed', 'ناموفق')], default='verified', max_length=16)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_verifications', to='disaster_recovery.databasebackupsnapshot')),
            ],
            options={
                'ordering': ('-verified_at',),
            },
        ),
    ]
