# Generated by Django 5.2.17 on 2026-09-15 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributedTraceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('span_id', models.CharField(max_length=64)),
                ('parent_span_id', models.CharField(blank=True, max_length=64, null=True)),
                ('service_name', models.CharField(default='django-api', max_length=64)),
                ('operation_name', models.CharField(max_length=128)),
                ('duration_ms', models.FloatField()),
                ('status', models.CharField(default='OK', max_length=16)),
                ('http_method', models.CharField(blank=True, default='GET', max_length=10)),
                ('http_status', models.IntegerField(default=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['trace_id'], name='observabili_trace_i_3fbaab_idx'), models.Index(fields=['-created_at'], name='observabili_created_204aad_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemMetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('uptime_percentage', models.FloatField(default=99.85)),
                ('p50_latency_ms', models.FloatField(default=42.0)),
                ('p95_latency_ms', models.FloatField(default=185.0)),
                ('p99_latency_ms', models.FloatField(default=340.0)),
                ('requests_per_second', models.FloatField(default=142.5)),
                ('error_rate_percentage', models.FloatField(default=0.15)),
                ('db_pool_active', models.IntegerField(default=18)),
                ('db_pool_available', models.IntegerField(default=82)),
                ('redis_hit_ratio', models.FloatField(default=96.4)),
                ('worker_queue_depth', models.IntegerField(default=4)),
                ('worker_active_tasks', models.IntegerField(default=12)),
                ('active_alerts_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['-timestamp'], name='observabili_timesta_84f2e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidentAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('title_fa', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], default='MEDIUM', max_length=16)),
                ('component', models.CharField(choices=[('API', 'API Gateway'), ('DATABASE', 'PostgreSQL Cluster'), ('REDIS', 'Redis Cache / Sentinel'), ('AI_GATEWAY', 'AI Model Gateway'), ('WORKER', 'Async Task Workers'), ('NETWORK', 'CDN / Network Edge')], default='API', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=16)),
                ('details', models.TextField(blank=True, default='')),
                ('threshold_breach', models.CharField(blank=True, default='', max_length=128)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_incident_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-triggered_at',),
                'indexes': [models.Index(fields=['status', '-triggered_at'], name='observabili_status_f5e798_idx')],
            },
        ),
    ]
