# Generated by Django 5.2.17 on 2026-09-05 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerMistakePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('grammar', 'Grammar & Structure'), ('lexical', 'Lexical & Vocabulary'), ('collocation', 'Collocations & Phrasing'), ('spelling', 'Spelling & Mechanics'), ('discourse', 'Discourse & Cohesion'), ('comprehension', 'Comprehension & Nuance'), ('pronunciation', 'Pronunciation & Stress'), ('strategy', 'Learning Strategy & Avoidance')], default='grammar', max_length=50)),
                ('tag', models.CharField(help_text='Normalized machine key, e.g. grammar.third_person_s', max_length=120)),
                ('title_fa', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('description_fa', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('l1_interference_note_fa', models.TextField(blank=True, help_text='Constructive explanation of Persian-English transfer root')),
                ('l1_interference_note_en', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('occasional', 'Occasional (Under evidence threshold)'), ('recurring', 'Recurring (Persistent pattern)'), ('disputed', 'Disputed (Excluded from recommendations)'), ('mastered', 'Mastered (Overcome through practice)')], default='occasional', max_length=20)),
                ('severity', models.CharField(choices=[('minor', 'Minor (Slip / Typo candidate)'), ('moderate', 'Moderate (Noticeable error)'), ('critical', 'Critical (Comprehension barrier)')], default='moderate', max_length=20)),
                ('evidence_count', models.PositiveIntegerField(default=1)),
                ('decay_score', models.FloatField(default=1.0, help_text='Decay multiplier for recency-based relevance')),
                ('is_disputed', models.BooleanField(default=False, help_text='If disputed, stops targeting in recommendations')),
                ('dispute_reason', models.TextField(blank=True)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-evidence_count', '-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='MistakeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_activity', models.CharField(default='exercise', help_text='placement, exercise, writing, speaking, srs, etc.', max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('raw_mistake_snippet', models.TextField(help_text='Sanitized excerpt displaying the error; strictly private')),
                ('correction_snippet', models.TextField(help_text='Natural target language correction')),
                ('explanation_fa', models.TextField(blank=True)),
                ('explanation_en', models.TextField(blank=True)),
                ('is_scrubbed', models.BooleanField(default=False, help_text='True if personal text snippet was scrubbed upon learner deletion request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_evidences', to=settings.AUTH_USER_MODEL)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='mistake_genome.learnermistakepattern')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='learnermistakepattern',
            index=models.Index(fields=['learner', 'status'], name='mistake_gen_learner_22c704_idx'),
        ),
        migrations.AddIndex(
            model_name='learnermistakepattern',
            index=models.Index(fields=['learner', 'category'], name='mistake_gen_learner_4727c4_idx'),
        ),
        migrations.AddIndex(
            model_name='learnermistakepattern',
            index=models.Index(fields=['learner', 'severity'], name='mistake_gen_learner_738377_idx'),
        ),
        migrations.AddConstraint(
            model_name='learnermistakepattern',
            constraint=models.UniqueConstraint(fields=('learner', 'tag'), name='unique_learner_mistake_tag'),
        ),
        migrations.AddIndex(
            model_name='mistakeevidence',
            index=models.Index(fields=['pattern', 'created_at'], name='mistake_gen_pattern_a21c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='mistakeevidence',
            index=models.Index(fields=['learner', 'created_at'], name='mistake_gen_learner_435304_idx'),
        ),
    ]
