# Generated by Django 5.2.17 on 2026-08-18 18:44

import accounts.managers
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('learner', 'Learner'), ('teacher', 'Teacher'), ('editor', 'Content editor'), ('support', 'Support'), ('administrator', 'Administrator')], default='learner', max_length=24)),
                ('preferred_locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], default='fa', max_length=2)),
                ('is_teacher_verified', models.BooleanField(default=False)),
                ('marketplace_eligible', models.BooleanField(default=False)),
                ('paid_class_eligible', models.BooleanField(default=False)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('email',),
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('terms', 'Terms'), ('privacy', 'Privacy'), ('marketing', 'Marketing')], max_length=24)),
                ('version', models.CharField(max_length=32)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], default='fa', max_length=2)),
                ('source', models.CharField(default='account', max_length=64)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-accepted_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'consent_type', 'version'), name='accounts_unique_consent_version')],
            },
        ),
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(db_index=True, max_length=254)),
                ('purpose', models.CharField(choices=[('phone_verify', 'Phone verification'), ('email_verify', 'Email verification'), ('password_reset', 'Password reset'), ('login', 'Login')], max_length=32)),
                ('code_hash', models.CharField(max_length=256)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['identifier', 'purpose', 'created_at'], name='accounts_otp_lookup_idx')],
            },
        ),
    ]
