# Generated by Django 5.2.17 on 2026-09-15 19:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSyncTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_session_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('drafts_received', models.PositiveIntegerField(default=0)),
                ('drafts_updated', models.PositiveIntegerField(default=0)),
                ('conflicts_detected', models.PositiveIntegerField(default=0)),
                ('payload_bytes', models.PositiveIntegerField(default=0)),
                ('network_effective_type', models.CharField(blank=True, default='unknown', max_length=16)),
                ('is_low_bandwidth', models.BooleanField(default=False)),
                ('client_user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_sync_telemetry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OfflineDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_type', models.CharField(choices=[('writing_submission', 'Writing Mentor Submission'), ('placement_checkpoint', 'Placement Test Checkpoint'), ('teacher_note', 'Teacher Class Note'), ('roleplay_response', 'Roleplay Scenario Response'), ('community_draft', 'Community Post Draft'), ('general_draft', 'General Resumable Draft')], db_index=True, default='general_draft', max_length=32)),
                ('resource_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('title', models.CharField(default='پیش\u200cنویس بدون عنوان', max_length=255)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('client_version', models.PositiveIntegerField(default=1)),
                ('server_version', models.PositiveIntegerField(default=1)),
                ('client_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('server_updated_at', models.DateTimeField(auto_now=True)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('is_conflict', models.BooleanField(default=False)),
                ('conflict_backup', models.JSONField(blank=True, default=dict)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-server_updated_at',),
                'indexes': [models.Index(fields=['user', 'draft_type', 'is_archived'], name='offline_syn_user_id_3adf3e_idx'), models.Index(fields=['user', 'resource_id'], name='offline_syn_user_id_0c8c1d_idx')],
            },
        ),
    ]
