# Generated by Django 5.2.17 on 2026-09-06 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('post', 'Community Post'), ('comment', 'Post Comment')], default='post', max_length=32)),
                ('target_id', models.CharField(db_index=True, max_length=64)),
                ('target_author_id', models.UUIDField(blank=True, null=True)),
                ('target_content_snapshot', models.TextField(help_text='Immutable snapshot of reported content at time of report')),
                ('reason', models.CharField(choices=[('copyright_infringement', 'نقض حقوق مالکیت معنوی و کپی\u200cرایت'), ('privacy_or_pii_leak', 'نشت اطلاعات حساس، هویتی یا اطلاعات خصوصی زبان\u200cآموز'), ('harassment_or_abuse', 'توهین، مزاحمت یا رفتار نامناسب'), ('spam_or_solicitation', 'اسپم، تبلیغات نامرتبط یا تقلب'), ('inappropriate_for_minors', 'محتوای نامناسب برای رده سنی کودکان و نوجوانان'), ('misinformation', 'اطلاعات نادرست و گمراه\u200cکننده آموزشی'), ('other', 'سایر موارد مغایر با قوانین جامعه اندورا')], db_index=True, default='other', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('sla_hours', models.PositiveIntegerField(default=24)),
                ('sla_deadline', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('in_review', 'در حال بازبینی توسط ناظر'), ('resolved', 'رسیدگی و تصمیم\u200cگیری شده'), ('dismissed', 'رد گزارش (فاقد تخلف)')], db_index=True, default='pending', max_length=24)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.CharField(choices=[('none', 'بدون اقدام'), ('content_removed', 'حذف محتوا از دید عمومی'), ('content_edited', 'ویرایش محتوا و حذف بخش نامناسب'), ('user_warned', 'ارسال اخطار رسمی به کاربر'), ('user_muted', 'بی\u200cصدا کردن کاربر (محرومیت از ثبت نظر و پست)'), ('user_suspended', 'مسدودسازی موقت یا دائم حساب کاربری')], default='none', max_length=32)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation Report',
                'verbose_name_plural': 'Moderation Reports',
                'ordering': ['sla_deadline', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('none', 'بدون اقدام'), ('content_removed', 'حذف محتوا از دید عمومی'), ('content_edited', 'ویرایش محتوا و حذف بخش نامناسب'), ('user_warned', 'ارسال اخطار رسمی به کاربر'), ('user_muted', 'بی\u200cصدا کردن کاربر (محرومیت از ثبت نظر و پست)'), ('user_suspended', 'مسدودسازی موقت یا دائم حساب کاربری')], max_length=32)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.CharField(max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='moderation.report')),
            ],
            options={
                'verbose_name': 'Moderation Audit Log',
                'verbose_name_plural': 'Moderation Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
