# Generated by Django 5.2.17 on 2026-09-15 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldenFlowVerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_flows', models.PositiveIntegerField(default=7)),
                ('passed_flows', models.PositiveIntegerField(default=7)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PASS', 'تأیید کامل'), ('WARN', 'هشدار غیربحرانی'), ('FAIL', 'رد شده')], db_index=True, default='PASS', max_length=16)),
                ('score', models.PositiveIntegerField(default=100)),
                ('flow_results', models.JSONField(blank=True, default=list)),
                ('rehearsed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='golden_flow_rehearsals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-rehearsed_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductionLaunchSignoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engineer_name', models.CharField(max_length=255)),
                ('role', models.CharField(default='Principal Launch Architect', max_length=100)),
                ('checklist_version', models.CharField(default='day60-launch-v1.0', max_length=64)),
                ('status', models.CharField(choices=[('APPROVED', 'تأیید نهایی انتشار (Production Approved)'), ('CONDITIONAL', 'تأیید مشروط (Conditional Approval)'), ('REVOKED', 'لغو مجوز انتشار (Launch Revoked)')], db_index=True, default='APPROVED', max_length=32)),
                ('verification_score', models.PositiveIntegerField(default=100)),
                ('confirmation_hash', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('signed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_signoffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-signed_at',),
            },
        ),
    ]
