# Generated by Django 5.2.17 on 2026-09-05 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleplaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id', models.CharField(max_length=64)),
                ('scenario_title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('turn_count', models.IntegerField(default=0)),
                ('max_turns', models.IntegerField(default=10)),
                ('goals_completed', models.JSONField(blank=True, default=list)),
                ('xp_awarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleplay_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roleplay Session',
                'verbose_name_plural': 'Roleplay Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleplayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_achieved_count', models.IntegerField(default=0)),
                ('total_goals_count', models.IntegerField(default=0)),
                ('communicative_score', models.IntegerField(default=80)),
                ('estimated_cefr', models.CharField(default='B1', max_length=16)),
                ('accomplishments_fa', models.JSONField(blank=True, default=list)),
                ('accomplishments_en', models.JSONField(blank=True, default=list)),
                ('feedback_mistakes', models.JSONField(blank=True, default=list)),
                ('vocabulary_extracted', models.JSONField(blank=True, default=list)),
                ('xp_earned', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='roleplay.roleplaysession')),
            ],
            options={
                'verbose_name': 'Roleplay Report',
                'verbose_name_plural': 'Roleplay Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleplayMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('character', 'Character'), ('learner', 'Learner'), ('system', 'System')], default='character', max_length=20)),
                ('sender_name', models.CharField(default='Assistant', max_length=100)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='roleplay.roleplaysession')),
            ],
            options={
                'verbose_name': 'Roleplay Message',
                'verbose_name_plural': 'Roleplay Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
