# Generated by Django 5.2.17 on 2026-09-09 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_skill', models.CharField(choices=[('speaking', 'اسپیکینگ و مکالمه'), ('writing', 'رایتینگ و تصحیح انشاء'), ('grammar', 'گرامر تحلیلی و کاربردی'), ('vocabulary', 'واژگان و اصطلاحات'), ('ielts_prep', 'آمادگی مهارت\u200cهای آیلتس'), ('pronunciation', 'تلفظ و لهجه'), ('general_english', 'انگلیسی عمومی و روزمره')], db_index=True, default='speaking', max_length=32)),
                ('target_subskill', models.CharField(blank=True, default='', max_length=128)),
                ('target_cefr_level', models.CharField(choices=[('A1', 'A1 - Elementary'), ('A2', 'A2 - Pre-Intermediate'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper-Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficiency'), ('unspecified', 'نامشخص / تعیین\u200cنشده')], db_index=True, default='unspecified', max_length=16)),
                ('short_description', models.TextField(help_text='توضیح هدف یا سوال یادگیری زبان\u200cآموز')),
                ('preferred_time_window', models.CharField(choices=[('today_afternoon', 'امروز بعدازظهر (۱۴ تا ۱۸)'), ('today_evening', 'امروز عصر و شب (۱۸ تا ۲۲)'), ('tomorrow_morning', 'فردا صبح (۹ تا ۱۳)'), ('tomorrow_afternoon', 'فردا بعدازظهر (۱۴ تا ۱۸)'), ('tomorrow_evening', 'فردا عصر و شب (۱۸ تا ۲۲)'), ('flexible', 'منعطف / هماهنگی با مدرس')], default='flexible', max_length=32)),
                ('duration_minutes', models.PositiveSmallIntegerField(choices=[(30, '30 دقیقه'), (45, '45 دقیقه'), (60, '60 دقیقه')], default=45)),
                ('online_format', models.CharField(choices=[('video', 'تماس تصویری'), ('audio', 'تماس صوتی'), ('async_review', 'بررسی و تصحیح آفلاین'), ('text_chat', 'گفتگوی متنی متمرکز')], default='video', max_length=24)),
                ('budget_max_toman', models.DecimalField(blank=True, decimal_places=0, help_text='حداکثر بودجه پیشنهادی زبان\u200cآموز به تومان', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('open', 'در انتظار دریافت پیشنهاد'), ('matched', 'دارای پیشنهادهای تطبیق\u200cیافته'), ('booked', 'رزرو قطعی شد'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده')], db_index=True, default='open', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_requests', to=settings.AUTH_USER_MODEL)),
                ('preferred_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_marketplace_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_toman', models.DecimalField(decimal_places=0, help_text='مبلغ پیشنهادی مدرس به تومان', max_digits=10)),
                ('proposed_start_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45)),
                ('online_format', models.CharField(choices=[('video', 'تماس تصویری'), ('audio', 'تماس صوتی'), ('async_review', 'بررسی و تصحیح آفلاین'), ('text_chat', 'گفتگوی متنی متمرکز')], default='video', max_length=24)),
                ('intro_note', models.TextField(blank=True, default='', help_text='پیام اختصاصی مدرس، راهکار تدریس و شیوه برگزاری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تصمیم زبان\u200cآموز'), ('accepted', 'پذیرفته شده'), ('declined', 'رد شده'), ('withdrawn', 'پس\u200cگرفته شده توسط مدرس'), ('expired', 'منقضی شده')], db_index=True, default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.marketplacerequest')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='marketplacerequest',
            name='matched_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_request', to='marketplace.teacheroffer'),
        ),
        migrations.AddIndex(
            model_name='teacheroffer',
            index=models.Index(fields=['request', 'status'], name='marketplace_request_61cfee_idx'),
        ),
        migrations.AddIndex(
            model_name='teacheroffer',
            index=models.Index(fields=['teacher', 'status'], name='marketplace_teacher_4bd5cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacheroffer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('request', 'teacher'), name='unique_pending_offer_per_teacher_request'),
        ),
        migrations.AddIndex(
            model_name='marketplacerequest',
            index=models.Index(fields=['status', '-created_at'], name='marketplace_status_5dbb14_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacerequest',
            index=models.Index(fields=['target_skill', 'status'], name='marketplace_target__41e549_idx'),
        ),
    ]
