# Generated by Django 5.2.17 on 2026-09-09 10:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_skill', models.CharField(choices=[('speaking', 'اسپیکینگ و مکالمه'), ('writing', 'رایتینگ و تصحیح انشاء'), ('grammar', 'گرامر تحلیلی و کاربردی'), ('vocabulary', 'واژگان و اصطلاحات'), ('ielts_prep', 'آمادگی مهارت\u200cهای آیلتس'), ('pronunciation', 'تلفظ و لهجه'), ('general_english', 'انگلیسی عمومی و روزمره')], default='speaking', max_length=32)),
                ('target_subskill', models.CharField(blank=True, default='', max_length=128)),
                ('duration_minutes', models.PositiveSmallIntegerField(choices=[(30, '30 دقیقه'), (45, '45 دقیقه'), (60, '60 دقیقه')], default=45)),
                ('online_format', models.CharField(choices=[('video', 'تماس تصویری'), ('audio', 'تماس صوتی'), ('async_review', 'بررسی و تصحیح آفلاین'), ('text_chat', 'گفتگوی متنی متمرکز')], default='video', max_length=24)),
                ('scheduled_start', models.DateTimeField(db_index=True)),
                ('scheduled_end', models.DateTimeField(db_index=True)),
                ('timezone_name', models.CharField(default='Asia/Tehran', max_length=64)),
                ('rate_toman', models.DecimalField(decimal_places=0, help_text='مبلغ قطعی رزرو به تومان', max_digits=10)),
                ('status', models.CharField(choices=[('confirmed', 'رزرو شده و قطعی'), ('reschedule_requested', 'درخواست جابجایی زمان'), ('in_progress', 'در حال برگزاری'), ('completed', 'پایان یافته'), ('cancelled_by_learner', 'لغو توسط زبان\u200cآموز'), ('cancelled_by_teacher', 'لغو توسط مدرس'), ('no_show_learner', 'عدم حضور زبان\u200cآموز'), ('no_show_teacher', 'عدم حضور مدرس'), ('disputed', 'مورد اختلاف')], db_index=True, default='confirmed', max_length=32)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='کلید یکتایی برای جلوگیری از ثبت تکراری', max_length=128, null=True, unique=True)),
                ('meeting_url', models.CharField(blank=True, default='', max_length=512)),
                ('session_notes', models.TextField(blank=True, default='', help_text='خلاصه جلسه و یادداشت\u200cهای آموزشی')),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('reschedule_proposed_start', models.DateTimeField(blank=True, null=True)),
                ('reschedule_proposed_end', models.DateTimeField(blank=True, null=True)),
                ('reschedule_note', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_bookings', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='marketplace.teacheroffer')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='marketplace.marketplacerequest')),
                ('reschedule_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_reschedules', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_start'],
                'indexes': [models.Index(fields=['status', 'scheduled_start'], name='marketplace_status_048074_idx'), models.Index(fields=['learner', 'status'], name='marketplace_learner_4135a3_idx'), models.Index(fields=['teacher', 'status'], name='marketplace_teacher_b0fb02_idx'), models.Index(fields=['scheduled_start', 'scheduled_end'], name='marketplace_schedul_e83c28_idx')],
            },
        ),
    ]
