# Generated by Django 5.2.17 on 2026-09-09 11:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_sessionbooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbooking',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='کلید یکتایی برای جلوگیری از ثبت تکراری (unique_booking_idempotency)', max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'رزرو شده و قطعی'), ('reschedule_requested', 'درخواست جابجایی زمان'), ('in_progress', 'در حال برگزاری'), ('completed', 'پایان یافته'), ('cancelled_by_learner', 'لغو توسط زبان\u200cآموز'), ('cancelled_by_teacher', 'لغو توسط مدرس'), ('no_show', 'عدم حضور در جلسه'), ('no_show_learner', 'عدم حضور زبان\u200cآموز'), ('no_show_teacher', 'عدم حضور مدرس'), ('disputed', 'مورد اختلاف')], db_index=True, default='confirmed', max_length=32),
        ),
        migrations.CreateModel(
            name='TeacherReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_rating', models.PositiveSmallIntegerField(help_text='امتیاز کلی از ۱ تا ۵', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_teaching', models.PositiveSmallIntegerField(default=5, help_text='کیفیت تدریس و تسلط', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_punctuality', models.PositiveSmallIntegerField(default=5, help_text='نظم و وقت\u200cشناسی', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_communication', models.PositiveSmallIntegerField(default=5, help_text='فن بیان، صبوری و اخلاق حرفه\u200cای', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(help_text='متن بازخورد و تجربه زبان\u200cآموز')),
                ('is_anonymous', models.BooleanField(default=False, help_text='نمایش نام زبان\u200cآموز به صورت مخفی/ناشناس')),
                ('masked_display_name', models.CharField(blank=True, default='', help_text='نام نمایشی ماسک\u200cشده (مثلاً سارا م.)', max_length=64)),
                ('status', models.CharField(choices=[('published', 'منتشر شده'), ('pending_moderation', 'در انتظار بررسی ناظر'), ('flagged', 'گزارش شده'), ('removed', 'حذف شده')], db_index=True, default='published', max_length=24)),
                ('teacher_reply', models.TextField(blank=True, default='', help_text='پاسخ رسمی مدرس به این بازخورد')),
                ('teacher_replied_at', models.DateTimeField(blank=True, null=True)),
                ('flag_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(help_text='جلسه تکمیل\u200cشده متناظر با این نظر', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='marketplace.sessionbooking')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reviews', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'status', '-created_at'], name='marketplace_teacher_89af64_idx'), models.Index(fields=['learner', 'status'], name='marketplace_learner_5b343d_idx')],
            },
        ),
    ]
