# Generated by Django 5.2.17 on 2026-09-09 11:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_sessionbooking_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAvailabilitySetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notice_lead_time_hours', models.PositiveSmallIntegerField(default=12, help_text='حداقل فاصله زمانی قبل از جلسه برای رزرو شدن به ساعت (پیش\u200cفرض ۱۲ ساعت)')),
                ('max_booking_ahead_days', models.PositiveSmallIntegerField(default=14, help_text='حداکثر بازه زمانی مجاز برای رزرو از قبل به روز (پیش\u200cفرض ۱۴ روز)')),
                ('default_session_duration_minutes', models.PositiveSmallIntegerField(default=45, help_text='مدت پیش\u200cفرض هر جلسه به دقیقه (۳۰، ۴۵، ۶۰ یا ۹۰)')),
                ('default_buffer_minutes', models.PositiveSmallIntegerField(default=15, help_text='فاصله استراحت پیش\u200cفرض بین دو جلسه به دقیقه (۰، ۱۰، ۱۵ یا ۳۰)')),
                ('auto_accept_bookings', models.BooleanField(default=True, help_text='تأیید خودکار رزروهای منطبق با زمان\u200cهای باز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAvailabilitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], help_text='روز هفته (شنبه=۰ تا جمعه=۶)')),
                ('start_time', models.TimeField(help_text='زمان آغاز دسترسی (ساعت و دقیقه به وقت تهران)')),
                ('end_time', models.TimeField(help_text='زمان پایان دسترسی (ساعت و دقیقه به وقت تهران)')),
                ('is_active', models.BooleanField(default=True, help_text='فعال یا غیرفعال بودن این بازه زمانی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['teacher', 'day_of_week', 'is_active'], name='marketplace_teacher_e0a1d6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='valid_availability_time_window')],
            },
        ),
        migrations.CreateModel(
            name='TeacherTimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(help_text='زمان آغاز مرخصی یا بلاک بودن (UTC)')),
                ('end_datetime', models.DateTimeField(help_text='زمان پایان مرخصی یا بلاک بودن (UTC)')),
                ('reason', models.CharField(blank=True, default='', help_text='علت مرخصی (سفر، امتحانات، تعطیلات رسمی و...)', max_length=255)),
                ('is_full_day', models.BooleanField(default=False, help_text='آیا مرخصی به صورت تمام\u200cروز است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['teacher', 'start_datetime', 'end_datetime'], name='marketplace_teacher_034775_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_datetime__lt', models.F('end_datetime'))), name='valid_time_off_window')],
            },
        ),
    ]
