# Generated by Django 5.2.17 on 2026-09-09 12:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_teacheravailabilitysetting_teacheravailabilityslot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPricingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='شناسه یکتای پلن (مانند launch_premium_90d)', max_length=64, unique=True)),
                ('name_fa', models.CharField(help_text='نام فارسی پلن اشتراک', max_length=120)),
                ('name_en', models.CharField(help_text='نام انگلیسی پلن اشتراک', max_length=120)),
                ('duration_days', models.PositiveIntegerField(default=90, help_text='طول دوره اشتراک به روز')),
                ('price_toman', models.DecimalField(decimal_places=0, default=Decimal('420000'), help_text='قیمت اشتراک به تومان', max_digits=12)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='فعال بودن پلن جهت خرید')),
                ('is_featured', models.BooleanField(default=False, help_text='برگزیده بودن پلن در صفحات قیمت\u200cگذاری')),
                ('features_fa', models.JSONField(blank=True, default=list, help_text='لیست مزایا و ویژگی\u200cهای پلن به فارسی')),
                ('note_fa', models.TextField(blank=True, default='قیمت اولیه برای دوره راه\u200cاندازی است و از بخش مدیریت سیستم قابل تنظیم است.')),
                ('note_en', models.TextField(blank=True, default='This is the launch-plan display price, centrally managed through administrator configuration.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price_toman'],
            },
        ),
        migrations.CreateModel(
            name='BookingDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_category', models.CharField(choices=[('teacher_absent', 'عدم حضور مدرس / غیبت'), ('learner_absent', 'عدم حضور زبان\u200cآموز'), ('technical_difficulties', 'مشکل فنی یا قطعی سیستم/اینترنت'), ('poor_quality', 'کیفیت نامطلوب جلسه / عدم تطابق با تخصص'), ('unprofessional_behavior', 'رفتار نامناسب یا نقض قوانین'), ('payment_disagreement', 'اختلاف مالی یا محاسباتی'), ('other', 'سایر موارد')], db_index=True, help_text='دسته\u200cبندی اصلی دلیل اختلاف', max_length=32)),
                ('description', models.TextField(help_text='توضیحات تفصیلی کاربر درباره مشکل جلسه (حداقل ۱۵ کاراکتر)')),
                ('evidence_notes', models.TextField(blank=True, default='', help_text='شواهد، لینک\u200cها یا یادداشت\u200cهای تکمیلی شاکی')),
                ('status', models.CharField(choices=[('open', 'در انتظار بررسی'), ('under_review', 'در حال بررسی کارشناس داوری'), ('resolved_full_refund', 'تایید بازگشت کامل وجه به زبان\u200cآموز'), ('resolved_partial_refund', 'تایید بازگشت بخشی از وجه'), ('resolved_pay_teacher', 'رد ادعا و واریز کامل به مدرس'), ('dismissed', 'رد ادعا بدون تغییر مالی')], db_index=True, default='open', help_text='وضعیت رسیدگی به اختلاف در پنل مدیریت', max_length=32)),
                ('refund_percentage', models.PositiveSmallIntegerField(default=0, help_text='درصد بازپرداخت به زبان\u200cآموز (۰ تا ۱۰۰)')),
                ('resolution_notes', models.TextField(blank=True, default='', help_text='توضیحات و دلایل رای صادره توسط تیم داوری اندورا')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(help_text='جلسه مورد اختلاف', on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='marketplace.sessionbooking')),
                ('opened_by', models.ForeignKey(help_text='کاربر شاکی (زبان\u200cآموز یا مدرس)', on_delete=django.db.models.deletion.CASCADE, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='کارشناس یا مدیر رسیدگی\u200cکننده به اختلاف', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='marketplace_status_3fbe40_idx'), models.Index(fields=['opened_by', '-created_at'], name='marketplace_opened__961677_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherOnboardingApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی کارشناس'), ('in_review', 'در حال بررسی مدارک'), ('approved', 'تأیید شده / فعال در بازارگاه'), ('rejected', 'رد درخواست'), ('revision_requested', 'نیازمند اصلاح یا بارگذاری مجدد مدارک')], db_index=True, default='pending', max_length=32)),
                ('national_id_number', models.CharField(blank=True, default='', help_text='شماره ملی مدرس جهت احراز هویت', max_length=20)),
                ('id_document_url', models.URLField(blank=True, default='', help_text='لینک تصویر کارت ملی یا شناسنامه')),
                ('degree_document_url', models.URLField(blank=True, default='', help_text='لینک دانشنامه یا گواهی تحصیلی دانشگاهی')),
                ('celta_tesol_document_url', models.URLField(blank=True, default='', help_text='لینک مدارک بین\u200cالمللی تدریس (TTC، CELTA، TESOL، DELTA)')),
                ('sample_teaching_url', models.URLField(blank=True, default='', help_text='لینک ویدیوی نمونه تدریس ۳ تا ۵ دقیقه\u200cای')),
                ('admin_notes', models.TextField(blank=True, default='', help_text='یادداشت\u200cهای محرمانه کارشناس بررسی\u200cکننده')),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='دلیل رد یا موارد نیازمند اصلاح ارسالی برای مدرس')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_teacher_applications', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.OneToOneField(help_text='کاربر مدرس متقاضی تدریس در بازارگاه', on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='marketplace_status_ffab72_idx')],
            },
        ),
    ]
