# Generated by Django 5.2.17 on 2026-09-09 12:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_platformpricingplan_bookingdispute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='وضعیت پرداخت قطعی جلسه'),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('confirmed', 'رزرو شده و قطعی'), ('reschedule_requested', 'درخواست جابجایی زمان'), ('in_progress', 'در حال برگزاری'), ('completed', 'پایان یافته'), ('cancelled_by_learner', 'لغو توسط زبان\u200cآموز'), ('cancelled_by_teacher', 'لغو توسط مدرس'), ('no_show', 'عدم حضور در جلسه'), ('no_show_learner', 'عدم حضور زبان\u200cآموز'), ('no_show_teacher', 'عدم حضور مدرس'), ('disputed', 'مورد اختلاف')], db_index=True, default='confirmed', max_length=32),
        ),
        migrations.CreateModel(
            name='BookingEscrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount_toman', models.DecimalField(decimal_places=0, help_text='کل مبلغ پرداختی زبان\u200cآموز به تومان', max_digits=12)),
                ('platform_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.15'), help_text='نرخ کارمزد پلتفرم (پیش\u200cفرض ۰.۱۵ یعنی ۱۵ درصد)', max_digits=4)),
                ('platform_commission_toman', models.DecimalField(decimal_places=0, default=0, help_text='سهم ناخالص پلتفرم اندورا از جلسه', max_digits=12)),
                ('teacher_net_toman', models.DecimalField(decimal_places=0, default=0, help_text='سهم خالص حق\u200cالتدریس مدرس (۸۵ درصد کل)', max_digits=12)),
                ('status', models.CharField(choices=[('held', 'نگهداری امن در حساب امانی'), ('released_to_teacher', 'تسویه با مدرس'), ('refunded_to_learner', 'استرداد کامل به زبان\u200cآموز'), ('partially_settled', 'تسویه توافقی درصدی')], db_index=True, default='held', max_length=32)),
                ('refund_amount_toman', models.DecimalField(decimal_places=0, default=0, help_text='مبلغ مسترد شده به زبان\u200cآموز در صورت لغو یا داوری', max_digits=12)),
                ('settlement_notes', models.TextField(blank=True, default='', help_text='یادداشت\u200cهای مالی تسویه یا استرداد حساب امانی')),
                ('funded_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(help_text='جلسه رزرو شده متصل به این حساب امانی', on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='marketplace.sessionbooking')),
            ],
            options={
                'ordering': ['-funded_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPayoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_toman', models.DecimalField(decimal_places=0, help_text='مبلغ درخواستی جهت تسویه و واریز به تومان', max_digits=12)),
                ('bank_shaba_number', models.CharField(help_text='شماره شبا حساب بانکی مدرس با پیشوند IR (۲۶ کاراکتر)', max_length=32)),
                ('bank_name', models.CharField(blank=True, default='', help_text='نام بانک عامل', max_length=64)),
                ('account_holder_name', models.CharField(blank=True, default='', help_text='نام صاحب حساب بانکی منطبق با کارت ملی', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده / در نوبت حواله پایا'), ('paid', 'واریز شد'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=24)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='یادداشت کارشناس مالی یا شماره پیگیری پایا')),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='دلیل رد درخواست واریز (مانند عدم تطابق شبا)')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance_toman', models.DecimalField(decimal_places=0, default=0, help_text='موجودی کل کیف پول به تومان', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('locked_toman', models.DecimalField(decimal_places=0, default=0, help_text='مبلغ مسدود شده در حساب امانی برای جلسات آتی به تومان', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'شارژ کیف پول'), ('booking_payment', 'پرداخت هزینه رزرو جلسه'), ('subscription_payment', 'خرید اشتراک پرمیوم'), ('escrow_hold', 'مسدودسازی امانی برای جلسه'), ('escrow_release', 'آزادسازی و واریز درآمد جلسه'), ('refund', 'استرداد وجه به کیف پول'), ('payout', 'برداشت و تسویه بانکی'), ('commission_deduction', 'کسر کارمزد پلتفرم')], db_index=True, max_length=32)),
                ('amount_toman', models.DecimalField(decimal_places=0, help_text='مبلغ تراکنش به تومان', max_digits=12)),
                ('balance_after_toman', models.DecimalField(decimal_places=0, help_text='موجودی کیف پول پس از تراکنش', max_digits=12)),
                ('tracking_code', models.CharField(db_index=True, help_text='کد پیگیری مالی یکتا', max_length=64, unique=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, default='', help_text='شناسه ارجاع خارجی (مانند کد رزرو یا شناسه تراکنش شاپرک)', max_length=128)),
                ('description', models.TextField(blank=True, default='', help_text='شرح فارسی تراکنش مالی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketplace.userwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('booking_session', 'رزرو جلسه آموزشی'), ('subscription_plan', 'اشتراک پرمیوم پلتفرم'), ('wallet_topup', 'شارژ کیف پول')], db_index=True, max_length=32)),
                ('gateway_provider', models.CharField(choices=[('zarinpal', 'درگاه زرین\u200cپال / شاپرک'), ('sandbox', 'درگاه شبیه\u200cساز آزمایشی'), ('wallet', 'کیف پول اندورا')], default='zarinpal', max_length=24)),
                ('amount_toman', models.DecimalField(decimal_places=0, help_text='مبلغ تراکنش به تومان (واحد رسمی نمایش و سفارش پلتفرم)', max_digits=12)),
                ('amount_rial', models.DecimalField(decimal_places=0, help_text='مبلغ معادل به ریال جهت ارسال به درگاه شاپرک (amount_toman * 10)', max_digits=14)),
                ('authority', models.CharField(blank=True, db_index=True, help_text='کد شناسه پرداخت درگاه زرین\u200cپال', max_length=128, null=True, unique=True)),
                ('ref_id', models.CharField(blank=True, db_index=True, help_text='شماره مرجع تراکنش شاپرک (RefID)', max_length=128, null=True)),
                ('card_pan', models.CharField(blank=True, default='', help_text='شماره کارت ماسک\u200cشده پرداخت\u200cکننده (مانند 603799******1234)', max_length=32)),
                ('status', models.CharField(choices=[('initiated', 'ایجاد شده'), ('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت موفق'), ('failed', 'ناموفق / انصراف'), ('refunded', 'مسترد شده')], db_index=True, default='initiated', max_length=24)),
                ('idempotency_key', models.CharField(db_index=True, help_text='کلید یکتایی پرداخت جهت جلوگیری از تراکنش تکراری', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='توضیحات سفارش و تراکنش')),
                ('gateway_callback_url', models.CharField(blank=True, default='', max_length=512)),
                ('is_sandbox', models.BooleanField(default=True, help_text='آیا تراکنش در محیط آزمایشی سندباکس انجام شده است')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='marketplace.sessionbooking')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='marketplace.platformpricingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='marketplace_user_id_05a306_idx'), models.Index(fields=['order_type', 'status'], name='marketplace_order_t_40aa10_idx')],
            },
        ),
    ]
