# Generated by Django 5.2.17 on 2026-09-14 17:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0006_sessionbooking_is_paid_alter_sessionbooking_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='نام یا عنوان تعرفه کارمزد (مانند: کارمزد استاندارد جلسات خصوصی)', max_length=128)),
                ('product_type', models.CharField(choices=[('session_1on1', 'جلسه خصوصی ۱ به ۱'), ('group_class', 'کلاس گروهی'), ('trial_session', 'جلسه آزمایشی / ارزیابی'), ('ielts_mock', 'شبیه\u200cساز و ماک آیلتس'), ('course_package', 'بسته آموزشی / دوره'), ('general', 'عمومی مارکت\u200cپلیس')], db_index=True, default='general', help_text='نوع محصول یا خدمت آموزشی مشمول این کارمزد', max_length=32)),
                ('rate_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='درصد کارمزد پلتفرم (مثلاً ۱۵.۰۰ یعنی ۱۵ درصد)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('fixed_fee_toman', models.DecimalField(decimal_places=0, default=0, help_text='کارمزد ثابت به تومان در صورت وجود', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='تاریخ و زمان آغاز اعتبار این تعرفه')),
                ('effective_to', models.DateTimeField(blank=True, db_index=True, help_text='تاریخ و زمان پایان اعتبار تعرفه (در صورت نامحدود بودن خالی بگذارید)', null=True)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='اولویت اعمال در صورت همپوشانی (عدد بزرگ\u200cتر اولویت دارد)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='فعال یا غیرفعال بودن این قانون')),
                ('description', models.TextField(blank=True, default='', help_text='توضیحات و مصوبه مالی مرتبط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-effective_from'],
                'indexes': [models.Index(fields=['product_type', 'is_active', 'effective_from'], name='ledger_comm_product_a201e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayoutAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submitted', 'ثبت درخواست تسویه توسط مدرس'), ('reviewed', 'بررسی کارشناسی و مدارک مالی'), ('approved', 'تأیید مرحله اول (کنترل داخلی)'), ('dual_signoff', 'امضای دوم تایید پرداخت (مدیر ارشد مالی)'), ('paid', 'ثبت حواله بانکی پایا / ساتنا و تسویه قطعی'), ('rejected', 'رد درخواست تسویه با ذکر دلیل')], db_index=True, max_length=32)),
                ('bank_transfer_reference', models.CharField(blank=True, default='', help_text='شناسه یا شماره پیگیری حواله پایا / ساتنا / شاپرک', max_length=128)),
                ('transfer_date', models.DateField(blank=True, help_text='تاریخ رسمی اجرای حواله بانکی', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='توضیحات و مستندات کنترل داخلی (بدون شماره کارت یا اسرار بانکی)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payout_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_audit_logs', to='marketplace.teacherpayoutrequest')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherTaxIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('national_id_masked', models.CharField(blank=True, default='', help_text='کد ملی ماسک\u200cشده جهت نمایش امن (مانند ۰۰۱****۳۴۵)', max_length=32)),
                ('national_id_hash', models.CharField(blank=True, db_index=True, default='', help_text='هش یک\u200cطرفه امن کد ملی جهت جلوگیری از حساب\u200cهای تکراری', max_length=64)),
                ('tax_file_number', models.CharField(blank=True, default='', help_text='شماره پرونده یا شناسه یکتای پرونده مالیاتی سامانه مودیان', max_length=64)),
                ('is_tax_exempt', models.BooleanField(default=False, help_text='مشمول معافیت مالیاتی بند ل ماده ۱۳۹ یا ماده ۹۵ ق.م.م')),
                ('withholding_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='نرخ مالیات تکلیفی قانونی در صورت شمول', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('30.00'))])),
                ('bank_shaba_number', models.CharField(blank=True, default='', help_text='شماره شبا با پیشوند IR', max_length=32)),
                ('bank_name', models.CharField(blank=True, default='', help_text='نام بانک عامل', max_length=64)),
                ('account_holder_name', models.CharField(blank=True, default='', help_text='نام و نام خانوادگی منطبق با حساب بانکی', max_length=128)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='تأیید تطابق کد ملی و شبا بانکی توسط واحد مالی')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_identity', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tax_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPayableLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('earning_pending', 'درآمد معلق در دوره رسیدگی به شکایات'), ('earning_available', 'درآمد قطعی و قابل تسویه'), ('payout_requested', 'مسدودسازی بابت درخواست تسویه بانکی'), ('payout_completed', 'تسویه موفق و واریز حواله پایا'), ('payout_rejected', 'استرداد به موجودی به دلیل رد درخواست تسویه'), ('refund_reversal', 'برگشت و کسر درآمد به دلیل استرداد جلسه'), ('commission_reversal', 'برگشت کارمزد پلتفرم بابت استرداد'), ('adjustment', 'تعدیل حسابداری با تایید مدیر ارشد مالی')], db_index=True, max_length=32)),
                ('amount_toman', models.DecimalField(decimal_places=0, help_text='مبلغ ردیف دفتر کل به تومان (مثبت: بستانکاری معلم، منفی: بدهکاری/برداشت)', max_digits=12)),
                ('gross_amount_toman', models.DecimalField(decimal_places=0, default=0, help_text='کل بهای ناخالص جلسه یا تراکنش پایه', max_digits=12)),
                ('commission_amount_toman', models.DecimalField(decimal_places=0, default=0, help_text='سهم کارمزد پلتفرم اندورا از این تراکنش', max_digits=12)),
                ('net_amount_toman', models.DecimalField(decimal_places=0, default=0, help_text='سهم خالص معلم', max_digits=12)),
                ('dispute_window_ends_at', models.DateTimeField(blank=True, db_index=True, help_text='زمان خاتمه بازه رسیدگی به شکایات که پس از آن وجه قابل تسویه می\u200cشود', null=True)),
                ('is_matured', models.BooleanField(db_index=True, default=False, help_text='آیا موعد بازبینی سپری شده و وجه در موجودی قطعی قرار دارد')),
                ('reference_code', models.CharField(db_index=True, help_text='شناسه سند مالی دفتر کل (مانند LED-2026-ABC123)', max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='شرح تراکنش دفتر کل (بدون ذخیره اطلاعات محرمانه بانکی)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_ledger_entries', to='marketplace.sessionbooking')),
                ('commission_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_entries', to='ledger.commissionrule')),
                ('payout_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_ledger_entries', to='marketplace.teacherpayoutrequest')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payable_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'entry_type', 'created_at'], name='ledger_teac_teacher_986e86_idx'), models.Index(fields=['teacher', 'is_matured', 'dispute_window_ends_at'], name='ledger_teac_teacher_dfa51a_idx')],
            },
        ),
    ]
