$ErrorActionPreference = 'Stop'
$repo = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
Set-Location $repo
$paths = @(
    '.env.example'
    'DAY06_INSTALL_WINDOWS.md'
    'DAY06_PACKAGE_MANIFEST.md'
    'apps\api\endoora_api\settings\base.py'
    'apps\api\endoora_api\urls.py'
    'apps\api\waitlist\__init__.py'
    'apps\api\waitlist\apps.py'
    'apps\api\waitlist\migrations\0001_initial.py'
    'apps\api\waitlist\migrations\__init__.py'
    'apps\api\waitlist\models.py'
    'apps\api\waitlist\serializers.py'
    'apps\api\waitlist\tests.py'
    'apps\api\waitlist\urls.py'
    'apps\api\waitlist\views.py'
    'apps\web\app\[slug]\page.tsx'
    'apps\web\app\api\waitlist\route.ts'
    'apps\web\app\en\[slug]\page.tsx'
    'apps\web\app\en\features\[feature]\page.tsx'
    'apps\web\app\en\legal\[legal]\page.tsx'
    'apps\web\app\en\page.tsx'
    'apps\web\app\features\[feature]\page.tsx'
    'apps\web\app\layout.tsx'
    'apps\web\app\legal\[legal]\page.tsx'
    'apps\web\app\opengraph-image.tsx'
    'apps\web\app\page.tsx'
    'apps\web\app\robots.ts'
    'apps\web\app\sitemap.ts'
    'apps\web\components\marketing\AnalyticsConsent.tsx'
    'apps\web\components\marketing\DocumentLocaleSync.tsx'
    'apps\web\components\marketing\FeaturePage.tsx'
    'apps\web\components\marketing\GenericPublicPage.tsx'
    'apps\web\components\marketing\HomePage.tsx'
    'apps\web\components\marketing\LegalPage.tsx'
    'apps\web\components\marketing\PublicShell.tsx'
    'apps\web\components\marketing\WaitlistForm.tsx'
    'apps\web\components\marketing\marketing.module.css'
    'apps\web\components\marketing\public-shell.module.css'
    'apps\web\lib\public-site.ts'
    'docs\operations\DAY_06_BACKUP_AND_ROLLBACK.md'
    'docs\operations\ENVIRONMENT_VARIABLES.md'
    'docs\product\DAY_06_PUBLIC_SITE.md'
    'docs\product\PROJECT_STATE_DAY06_DRAFT.md'
    'docs\quality\DAY_06_ACCEPTANCE_GATE.md'
    'package.json'
    'scripts\backup_day06.ps1'
    'scripts\check-public-site.mjs'
    'scripts\stage_day06.ps1'
)
git add -- $paths
Write-Host 'Day 06 package files staged. Review with: git status'
