# Generated by Django 5.2.17 on 2026-09-15 12:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPurgeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('automated_cron', 'Automated Cron Schedule'), ('manual_operator', 'Manual Operator Trigger'), ('user_requested', 'User Immediate Request')], default='automated_cron', max_length=32)),
                ('accounts_erased', models.PositiveIntegerField(default=0)),
                ('audio_files_purged', models.PositiveIntegerField(default=0)),
                ('stale_otps_purged', models.PositiveIntegerField(default=0)),
                ('stale_exports_purged', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('partial', 'Partial Execution'), ('dry_run', 'Dry Run'), ('failed', 'Failed')], default='completed', max_length=24)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_data_purges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-executed_at',),
            },
        ),
        migrations.CreateModel(
            name='PrivacyConsentPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('functional_storage', models.BooleanField(default=True, editable=False)),
                ('analytics_processing', models.BooleanField(default=True)),
                ('ai_model_training_telemetry', models.BooleanField(default=True)),
                ('marketing_communications', models.BooleanField(default=False)),
                ('locale', models.CharField(default='fa', max_length=2)),
                ('policy_version', models.CharField(default='day52-2026-09-15', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_ip', models.CharField(blank=True, default='', max_length=45)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
