# Generated by Django 5.2.17 on 2026-08-21 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SrsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=120)),
                ('meaning_fa', models.CharField(max_length=255)),
                ('objective_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('new', 'new'), ('learning', 'learning'), ('review', 'review'), ('mastered', 'mastered')], default='new', max_length=20)),
                ('interval_days', models.PositiveIntegerField(default=1)),
                ('repetition', models.PositiveIntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('due_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SrsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('previous_interval_days', models.PositiveIntegerField(default=1)),
                ('new_interval_days', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='srs.srsitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='srsitem',
            index=models.Index(fields=['learner', 'due_at'], name='srs_srsitem_learner_a80ffd_idx'),
        ),
    ]
