# Generated by Django 5.2.17 on 2026-09-05 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SrsCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=120)),
                ('lemma', models.CharField(max_length=120)),
                ('part_of_speech', models.CharField(blank=True, default='unknown', max_length=40)),
                ('meaning_fa', models.CharField(blank=True, max_length=255)),
                ('example_sentence', models.TextField(blank=True)),
                ('source_text', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, default='activity', max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('phonetic', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('ignored', 'ignored')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='srsitem',
            options={'ordering': ['due_at']},
        ),
        migrations.AlterModelOptions(
            name='srsreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='srsitem',
            name='audio_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='srsitem',
            name='collocation_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='srsitem',
            name='collocation_fa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='srsitem',
            name='example_sentence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='srsitem',
            name='is_leech',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='srsitem',
            name='lapse_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='srsitem',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='srsitem',
            name='leech_action',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='srsitem',
            name='lemma',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='srsitem',
            name='part_of_speech',
            field=models.CharField(blank=True, default='unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='srsitem',
            name='phonetic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='srsitem',
            name='sense_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='srsitem',
            name='source_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='srsitem',
            name='source_type',
            field=models.CharField(blank=True, default='activity', max_length=50),
        ),
        migrations.AddField(
            model_name='srsreview',
            name='new_ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='srsreview',
            name='previous_ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='srsreview',
            name='response_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='srsreview',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='1=Again, 2=Hard, 3=Good, 4=Easy (or 5 for legacy)'),
        ),
        migrations.AddIndex(
            model_name='srsitem',
            index=models.Index(fields=['learner', 'is_leech'], name='srs_srsitem_learner_5db247_idx'),
        ),
        migrations.AddIndex(
            model_name='srsitem',
            index=models.Index(fields=['learner', 'status'], name='srs_srsitem_learner_a7caac_idx'),
        ),
        migrations.AddConstraint(
            model_name='srsitem',
            constraint=models.UniqueConstraint(fields=('learner', 'lemma', 'part_of_speech'), name='unique_learner_lemma_pos'),
        ),
        migrations.AddField(
            model_name='srscandidate',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='srscandidate',
            index=models.Index(fields=['learner', 'status'], name='srs_srscand_learner_f35d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='srscandidate',
            index=models.Index(fields=['learner', 'lemma'], name='srs_srscand_learner_89f46b_idx'),
        ),
    ]
