# Generated by Django 5.2.17 on 2026-08-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymission',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='ready', max_length=20),
        ),
    ]
