from django.urls import path
from .views import (
    teacher_eligibility_view,
    marketplace_requests_view,
    marketplace_request_detail_view,
    cancel_marketplace_request_view,
    request_offers_view,
    teacher_offers_workspace_view,
    withdraw_teacher_offer_view,
    accept_teacher_offer_view,
    bookings_collection_view,
    booking_detail_view,
    cancel_booking_view,
    request_reschedule_view,
    respond_reschedule_view,
    start_booking_session_view,
    complete_booking_session_view,
    public_teachers_directory_view,
    teacher_public_profile_view,
    teacher_reviews_list_view,
    booking_review_view,
    reply_to_review_view,
    flag_review_view,
    teacher_availability_view,
    teacher_time_off_list_create_view,
    teacher_time_off_delete_view,
    teacher_availability_settings_view,
    public_teacher_available_slots_view,
)

urlpatterns = [
    path("eligibility/", teacher_eligibility_view, name="marketplace_teacher_eligibility"),
    path("requests/", marketplace_requests_view, name="marketplace_requests"),
    path("requests/<uuid:request_id>/", marketplace_request_detail_view, name="marketplace_request_detail"),
    path("requests/<uuid:request_id>/cancel/", cancel_marketplace_request_view, name="marketplace_request_cancel"),
    path("requests/<uuid:request_id>/offers/", request_offers_view, name="marketplace_request_offers"),
    path("offers/", teacher_offers_workspace_view, name="marketplace_teacher_offers"),
    path("offers/<uuid:offer_id>/withdraw/", withdraw_teacher_offer_view, name="marketplace_offer_withdraw"),
    path("offers/<uuid:offer_id>/accept/", accept_teacher_offer_view, name="marketplace_offer_accept"),

    # Day 38: Booking & Scheduling Endpoints
    path("bookings/", bookings_collection_view, name="marketplace_bookings"),
    path("bookings/create_direct/", bookings_collection_view, name="marketplace_booking_create_direct"),
    path("bookings/<uuid:booking_id>/", booking_detail_view, name="marketplace_booking_detail"),
    path("bookings/<uuid:booking_id>/cancel/", cancel_booking_view, name="marketplace_booking_cancel"),
    path("bookings/<uuid:booking_id>/reschedule/", request_reschedule_view, name="marketplace_booking_reschedule"),
    path("bookings/<uuid:booking_id>/reschedule/respond/", respond_reschedule_view, name="marketplace_booking_reschedule_respond"),
    path("bookings/<uuid:booking_id>/start/", start_booking_session_view, name="marketplace_booking_start"),
    path("bookings/<uuid:booking_id>/complete/", complete_booking_session_view, name="marketplace_booking_complete"),

    # Day 39: Teacher Public Directory, Profile & Review Endpoints
    path("teachers/", public_teachers_directory_view, name="marketplace_public_teachers"),
    path("teachers/<uuid:teacher_id>/", teacher_public_profile_view, name="marketplace_teacher_public_profile"),
    path("teachers/<uuid:teacher_id>/reviews/", teacher_reviews_list_view, name="marketplace_teacher_reviews"),
    path("bookings/<uuid:booking_id>/review/", booking_review_view, name="marketplace_booking_review"),
    path("reviews/<uuid:review_id>/reply/", reply_to_review_view, name="marketplace_review_reply"),
    path("reviews/<uuid:review_id>/flag/", flag_review_view, name="marketplace_review_flag"),
    # Day 40: Teacher Availability Calendar & Time-Off Endpoints
    path("teacher/availability/", teacher_availability_view, name="teacher_availability"),
    path("teacher/availability/time-off/", teacher_time_off_list_create_view, name="teacher_time_off_list_create"),
    path("teacher/availability/time-off/<uuid:time_off_id>/", teacher_time_off_delete_view, name="teacher_time_off_delete"),
    path("teacher/availability/settings/", teacher_availability_settings_view, name="teacher_availability_settings"),
    path("teachers/<uuid:teacher_id>/available-slots/", public_teacher_available_slots_view, name="public_teacher_available_slots"),
]
