# Generated by Django 5.2.17 on 2026-09-04 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placementanswer',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='placementsession',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='placementanswer',
            name='question_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_answers', to='questions.questionversion'),
        ),
    ]
